### ISSUE TITLE
Headers overlap on mobile

### ISSUE THREAD

**Issue by mosheduminer** [tauri-apps/tauri-docs#10]
The headers of every page are stacked on mobile, but they overlap.
![Screenshot (35)](https://user-images.githubusercontent.com/47164590/78790810-0cbff100-797d-11ea-84c8-0905c8e74f83.png)

**Comment by nklayman** [comment]
Will be fixed by #14.

**Comment by nothingismagick** [comment]
Is this still happening with the v2?

**Comment by nklayman** [comment]
Nope, the navigation has changed and this is no longer an issue.
