### ISSUE TITLE
wrong content of mobile prerequisites of macOS

### ISSUE THREAD

**Issue by BillGoldenWater** [tauri-apps/tauri-docs#1017]
see image
![](https://media.discordapp.net/attachments/1051122769200414751/1051122944232927293/image.png)

and linux prerequisites also has a false at tail of env var section

```bash
export ANDROID_HOME="$HOME/Library/Android/sdk"
export NDK_HOME="$ANDROID_HOME/ndk/25.0.8775105"
```

**Comment by FabianLars** [comment]
(Assigning Lucas because i don't know if just copy pasting it from the other platform works)

**Comment by simonhyll** [comment]
I'm pretty sure I can close this one as completed as we've since made updates to the docs that I believe address this issue.
