### ISSUE TITLE
[docs] differences in dev and bundle, running an exec process

### ISSUE THREAD

**Issue by jswhisperer** [tauri-apps/tauri-docs#102]
Very cool library I just wrote a [post](https://gregbenner.life/web-view-apps-on-your-os/) looking at similar

Looking at the docs I can't find a difference with dev and bundle for running a bundled binary like:
```
"build": {
    "distDir": ".",
    "devPath": "http://localhost:3666",
    "beforeDevCommand": "vue ui --headless --port 3666",
    "beforeBuildCommand": "vue ui --headless --port 3666"
  },
```

The dev works fine but the release hangs, I'm assuming it''s waiting for the server to exit. Do I need to include it as an "externalBinary" instead or run it as a spawned exec process? I'm not Rust savy, more node.js hopefully this isnt a stupid question.

Thanks!

**Comment by simonhyll** [comment]
Well since you've set the distDir to . it's likely simply a matter of it trying to add e.g. the target folder in an infinite loop, hence hanging. This is more of a support question and not an issue, so I'll close it. Feel free to head on over to the Discord for further support! 🙂
