### ISSUE TITLE
next docs contains a random "false" after codeblock item

### ISSUE THREAD

**Issue by VividLemon** [tauri-apps/tauri-docs#1058]
![image](https://user-images.githubusercontent.com/31498096/211055412-99a3cd9e-1368-470e-907b-02df741f397e.png)
This is under debian*

I'm not sure why, but this codeblock has a "false" after it. I'm not sure where this is, but it was breaking my export when copy/pasting. I don't think this intentional, I also cannot find it in the docs and where the false is coming from. 

https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/linux/#2-install-the-android-sdk-and-ndk

**Comment by FabianLars** [comment]
Thanks for the report :)
