### ISSUE TITLE
Proper links needs to be connected in https://tauri.app/about/governance

### ISSUE THREAD

**Issue by ItsRoy69** [tauri-apps/tauri-docs#1074]
When we click on the attached links in Code of Conduct and Social Contract we see that the link given is master but that needs to be fixed to main orelse the below line will appear

![image](https://user-images.githubusercontent.com/78967360/214230509-904f062b-cb55-46f2-a3cc-7faa3ae9a0e7.png)

![image](https://user-images.githubusercontent.com/78967360/214230337-18d8da96-7aa6-4b16-84c4-5bb9bff77248.png)

I can work on this issue

**Comment by ItsRoy69** [comment]
I can work on this issue

**Comment by lorenzolewis** [comment]
That would be awesome @ItsRoy69. Be sure for an PRs you put in that you have Commit Signing turned on https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
