### ISSUE TITLE
Proper issue issue templates would make it easier for contributors to contribute and be specific like other repositories

### ISSUE THREAD

**Issue by ItsRoy69** [tauri-apps/tauri-docs#1075]
It would look like this

![image](https://user-images.githubusercontent.com/78967360/214230801-e8ef698e-5805-4160-ab7e-d26877e363ea.png)

**Comment by FabianLars** [comment]
In theory i agree, i always like to see issue templates, _but_ i have no ideas what types of templates we could use here and what they would actually look like. Do you have any ideas?

**Comment by lorenzolewis** [comment]
One thing I'm wanting to work on is to create stub pages on the website. These would be pages inviting community members to contribute. It doesn't address a issue template but could help those who wish to contribute

**Comment by simonhyll** [comment]
I'll track this for 2.0, we can improve the current templates a bit.

**Comment by simonhyll** [comment]
I went ahead and added some issue templates. Feel free to offer input on them, closing the issue as completed for now.
