### ISSUE TITLE
[docs] It Would be Great to Have Minimal Example Applications for Most of the "Patterns"

### ISSUE THREAD

**Issue by zicklag** [tauri-apps/tauri-docs#109]
I was just thinking that it would be great to have a minimal example application demonstrating the "Lockdown" pattern, but then I realized it would be good to have minimal demonstrations of each of the different patterns to show users what each one looks like in practice.

Obviously the ones that aren't ready yet don't need examples yet.

**Comment by zicklag** [comment]
Sounds good. Keep up the good work! I *might* ( big might ) end up tackling some of this stuff. I've been really excited to get into Tauri for months and just got the chance to start using it. I'll probably be opening up issues for what I run into as I go and taking on the ones that I can.

**Comment by zoubingwu** [comment]
How it this going or is there any example project on GitHub? Did some search but couldn't find one 😢

**Comment by FabianLars** [comment]
@zoubingwu Nothing new in that regard. The best practice atm is to just keep your `allowlist` as minimal as possible (only enable the stuff you actually use)

**Comment by simonhyll** [comment]
Just so I get the lingo correct, is this the isolation and brownfield patterns we're talking about? I'll track it for 2.0 for now as being about that.

**Comment by FabianLars** [comment]
Nope, it's something else we've removed from the docs a while ago (it was meant to be temporary until they were updated...). The dev branch still has the md files though https://github.com/tauri-apps/tauri-docs/tree/aa2192cffd03654aff7405f39e28e75691e6e9e4/docs/references/architecture/recipes (used to be called patterns not recipes)

**Comment by simonhyll** [comment]
Do we want them to be "upgraded" to version 2.0 one way or another or are we throwing them out? Can I close this issue?

**Comment by FabianLars** [comment]
I don't see them being reintegrated as anything close to what they were so imo we can close this issue.
