### ISSUE TITLE
[docs] added an example for svelte with tailwindcss

### ISSUE THREAD

**Issue by goldcoders** [tauri-apps/tauri-docs#111]
if someone need a starter or a reference on tauri with Svelte and TailwindCSS

[Check This Repo](https://github.com/goldcoders/rhugos)

**Comment by Laegel** [comment]
That's awesome, @goldcoders , thanks for your initiative! Svelte and TailwindCSS are often mentioned, I guess it will help many people. :D

@nothingismagick : I wonder... I expected the showcase to be the page where we list built projects, not bootstrap/starter projects. 
The current showcase page is still young and meant to evolve, that's for sure.
We may add that to the showcase with a nice filter system (either tool or app, for example); as Tauri's popularity grows everyday, I expect a lot of additions to the list and having this filter system would make it more future-proof. 
Else, we may create another page, dedicated to tools and other awesome stuff that would enhance Tauri's DX. 
I guess only devs are going to browse the showcase, anyway, so mixing everything at the same place wouldn't be that bad.
