### ISSUE TITLE
[docs] Small mistakes that can be quick fixed

### ISSUE THREAD

**Issue by vdang-crabnebula** [tauri-apps/tauri-docs#1123]
Hey, first thanks for your work

Just going through the guides and I noticed some small mistakes here and there.
Thought that could be helpful to you. 

## Guides -> Quick Start -> HTML, CSS ,and Javascript
Typo in the section title `Quick Start -> HTML, CSS ,and Javascript` with extra comma. `HTML, CSS, and Javascript` should be  `HTML, CSS and Javascript`

## Guides -> Testing -> Mocking Tauri APIs
-  there is no information on where/which file the code blocks should be pasted to
- no information is given that the code blocks are in typescript 
- nitpicking here but for consistency either use semicolon or not for code:
 ```
import { beforeAll, expect, test } from "vitest";
import { randomFillSync } from "crypto";

import { mockIPC } from "@tauri-apps/api/mocks"  <--- no semicolon
import { invoke } from "@tauri-apps/api/tauri";
```

## Guides -> Testing -> WebDriver Testing
- The subsections are in the wrong order
We have: `Selenium -> Setup Example -> WebdriverIO`
It shoule be: `Setup Example -> WebdriverIO -> Selenium`

## Guides -> Building -> Linux Bundle 
No instructions are given concerning how to build an AppImage from a Tauri project 

## Guides -> Building -> Reducing App Size 
For consistency also add link to:
- `cargo-bloat` -> https://github.com/RazrFalcon/cargo-bloat
- `rollup-plugin-visualize` -> https://github.com/btd/rollup-plugin-visualizer

**Comment by FabianLars** [comment]
The first one is an Oxford comma (was that its name?), so technically it's correct but i'll let our english professor Lorenzo decide on that one :D

I totally agree with the rest though, thanks for the report 👍

**Comment by FabianLars** [comment]
Also i'm not sure how to solve the issues in the mocking guide. maybe @JonasKruckenberg, the author of that guide has an idea? (when you're available ofc, i know you're busy with RustNation).

For the rest i opened #1124

**Comment by lorenzolewis** [comment]
> The first one is an Oxford comma (was that its name?), so technically it's correct but i'll let our english professor Lorenzo decide on that one :D

Oxford comma is correct. I'm slowly being converted away from it and in some mocks of the new site have been going with "HTML, CSS and JavaScript". I only use it if an item on the list contains "and" and without the comma the list could be confusing. 

If we change it let's update Style on https://github.com/tauri-apps/tauri-docs/blob/dev/.github/CONTRIBUTING.md to indicate we don't use Oxford commas so we have a reference
