### ISSUE TITLE
How to translate this document

### ISSUE THREAD

**Issue by OlalalalaO** [tauri-apps/tauri-docs#1129]
I want to do some translation work, how should I proceed?

**Comment by lorenzolewis** [comment]
Hi @OlalalalaO Thanks for reaching out! What language(s) are you interested in? We host all of our translations on the tauri-docs repo (I've transferred this issue to that repo).

We've currently frozen translations as we're building out a new website that will launch this spring. You can keep track of the progress here: https://github.com/orgs/tauri-apps/projects/18

**Comment by simonhyll** [comment]
Closing this as it's a question, not an issue.
