### ISSUE TITLE
Copy button on docs websites ads $

### ISSUE THREAD

**Issue by snnsnn** [tauri-apps/tauri-docs#113]
Hi, 

Copy button for terminal commands adds $ symbol at the beginning, you have to delete them manually after pasting to terminal, which defeats the whole purpose of copy button. It would be better if $ is implemented as css ::before content.

Thanks.

**Comment by Laegel** [comment]
Hey @snnsnn !
Thanks for the issue. I agree with you, this `$` is quite annoying in this context. I'm not sure the CSS solution would help, though, since we can't determine easily what lines should get the symbol and which one shouldn't. Maybe removing the sign on copy would be better.
