### ISSUE TITLE
Android Studio JDK path for Windows and Linux in v2.0 is wrong

### ISSUE THREAD

**Issue by dklassic** [tauri-apps/tauri-docs#1187]
Been testing out running a tauri app on Android in recent days and I've notice v2.0 document on Android Studio's JDK path seems to be wrong on [Windows](https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/windows#1-configure-jdk) and [Linux](https://next--tauri.netlify.app/next/guides/getting-started/prerequisites/linux#1-configure-jdk).
Both stated the JDK is installed under `<path to Android Studio>/jre` but the actual path is `<path to Android Studio>/jbr`.

It would seem like the path used to be in `jre` but it was moved to `jbr` by Android Studio at some point.

**Comment by amrbashir** [comment]
That is correct, the path has indeed changed recently from `jre` to `jbr`

**Comment by FabianLars** [comment]
So if it was _recently_ we should mention both for a while?
