### ISSUE TITLE
tauri.app misconfigured

### ISSUE THREAD

**Issue by jaller94** [tauri-apps/tauri-docs#1234]
The following screenshot shows the broken build that's currently live at https://tauri.app/.

![Your Docusaurus site did not load properly. A very common reason is a wrong site [baseUrl configuration](https://docusaurus.io/docs/docusaurus.config.js/#baseurl).](https://user-images.githubusercontent.com/10872136/236711723-ab231ac8-bdd0-4354-9675-32ed7330c15f.png)

**Comment by FabianLars** [comment]
Thanks for the report :)

We have no real idea what's happening here and we've had less than a handful of people report this over the years. It seems to always be related to user-side proxies and i have no idea what we could do to fix that.

In case it helpt, the [last person](https://discord.com/channels/616186924390023171/1064858173741223988/1064867945664237629)'s solution was:
> I solved this by adding these two domains into bypassing list in my proxy which is clash:
tauri.app
> d33wubrfki0l68.cloudfront.net

Hopefully this will be less of an issue with our beta docs (https://tauri-dev.netlify.app/) once they go live 🙏

**Comment by jaller94** [comment]
Ah, to me it looked like a broken static site.

FYI, Firefox's enhanced tracking protection blocked the assets on cloudfront.

**Comment by FabianLars** [comment]
There seems to be another additional condition because i and a few other team members use firefox with the strictest settings (and blocker extensions) too and we've never had any issues 🤔

Anyway, we'll keep it mind, thanks!
