### ISSUE TITLE
[docs] broken link to rust api

### ISSUE THREAD

**Issue by drmason13** [tauri-apps/tauri-docs#124]
The link on this page: https://tauri.studio/en/docs/development/intro
Named "Rust API"
goes to: https://tauri.studio/en/docs/api/rust/tauri/config/fn.get

Which led to the tauri 404: Page Not Found

I'm browsing on Android Chrome.

**Comment by Laegel** [comment]
@drmason13 Thanks for spotting this 404.
The Rust API can still be reached through API > Rust > [crate]. From there, you have a link for each Rust entity (function, struct, ...).

**Comment by drmason13** [comment]
Hiya, I found the broken link.
It's in docs/usage/intro.md

docs/en/usage/intro.md

tauri needs replacing with tauri_api in the URL

https://tauri.studio/en/docs/api/rust/tauri_api/config/fn.get/

Assuming that's the equivalent.

The crate's standard rust docs are also helpful:
https://docs.rs/tauri-api/latest/tauri_api/

**Comment by Laegel** [comment]
Thanks @drmason13 ! This is something that's missing and should be improved, indeed. :+1:
