### ISSUE TITLE
Tauri Website Beta Issue Dashboard

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#1244]
This is used to track the current open issues on the new Tauri website (currently hosted at https://tauri-dev.netlify.app). As we find and fix issues we'll update this issue. Feel free to comment any issues you find on this issue and we'll get them patched up. If there's something you'd like to help with then feel free to submit a PR against the `beta` branch for it (and thank you in advance! 🧡 )

## Issues

- [ ] Build out blog functionality (currently linking to production site)
- [x] Build out About and Index pages (currently linking to production site)
- [x] Fix any broken images in the guides (https://tauri-dev.netlify.app/docs/1/)
- [ ] Tweak font colours on documentation pages so they aren't pure white
- [ ] Add in charts to pages like https://tauri-dev.netlify.app/docs/1/references/architecture/ (might just make those as an SVG instead of adding a Mermaid.js integration)
- [ ] Create a "Skip to Content" component for A11Y
- [ ] SEO/metadata for all pages (including title attribute)
- [x] Fix links on https://beta.tauri.app/api/js/1/ (this is due to how HTML link resolution and Markdown link resolution are different)

**Comment by trobonox** [comment]
Two things I've noticed, mobile-specific issues:
- Lack of whitespace between the header at the top and page content
- Overflow in x-direction on pages with big tables (like the tauri config page) creates overflow for the entire page which breaks the scrolling experience; See stable page for a better experience where only the tables scroll on an individual basis and other overflow is hidden

**Comment by lorenzolewis** [comment]
Closing this one out as we've switched over to using https://starlight.astro.build
