### ISSUE TITLE
Show how to build for aarch64/universal macos targets with tauri-action

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri-docs#1273]
Now that tauri-action@v0.4 is released we should update the docs a bit to show how to use a build matrix.

I wonder if we need to split up the cross-platform page in the future if we want to go more in-depth about the action, add more experimental local cross-platform building, or have community members add guides for other CI sites.

Or maybe we should move the local building stuff into their respective building pages? 🤔 (so the experimental windows cross target to windows.md)

**Comment by simonhyll** [comment]
Gonna track this for 2.0. I feel like this may be best documented in the Build guide under a section about CI/CD. We definitely need to inform about the action somewhere.

**Comment by FabianLars** [comment]
I updated the v1 docs for x64/aarch64 builds, together with the already existing mention of the universal target in the building guide i assume this is enough.
