### ISSUE TITLE
Missing `--release` flag in doc's publishing page

### ISSUE THREAD

**Issue by thekingofcity** [tauri-apps/tauri-docs#1280]
https://tauri.app/v1/guides/distribution/publishing

This page states a `cargo build` command will give binary under `src-tauri/target/release/[app name]`. However, I still get the debug binary as the command output `Finished dev [unoptimized + debuginfo] target(s) in 1m 10s` at the end.

It should be updated to `cargo build --release` so that there will be a `release` directory and `Finished release [optimized] target(s) in 1m 39s` at the end of the command output.

If `cargo build` should make a binary in `src-tauri/target/release/[app name]`, let me know if I'm doing something wrong. I'm also willing to open a Pull Request if it is not.

**Comment by FabianLars** [comment]
Thanks for reaching out :)

The docs mention `cargo tauri build` not `cargo build`. Tauri's `build` command will automatically add the `--release` flag to the `cargo build` call.
