### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by jbolda** [tauri-apps/tauri-docs#13]
We currently have a code of conduct link in the footer which links to the main repo markdown file page. I assume we want to have the code of conduct translated so this should likely become it's own page. Also, items in the footer are not available for translation so we may need to move the link to a translatable location.

**Comment by Laegel** [comment]
Header links are translatable. But Docusaurus doesn't allow dropdowns in the header so we need to choose wisely what to display there; and I think CoC isn't the most important thing to show in the headers.
Maybe a dedicated section with important links in the homepage?

**Comment by jbolda** [comment]
That would make sense to me. A "community" section on the homepage which points to a specific page for the CoC.

**Comment by Laegel** [comment]
Since we're now on V2 and translation is not blocking us (for now), this can be done.

**Comment by nothingismagick** [comment]
Can we source the code of conduct from a repo?

**Comment by Laegel** [comment]
@nothingismagick What do you mean? Have a reference in the docs to a repo containing the CoC?

**Comment by nothingismagick** [comment]
https://github.com/tauri-apps/tauri/blob/dev/.github/CODE_OF_CONDUCT.md

**Comment by Laegel** [comment]
I don't think there's a builtin way to fetch the content and render it. We may create a component for that purpose.
Might be premature but we'll have to handle translation and I think having a copy in the docs will be mandatory.

**Comment by nothingismagick** [comment]
ok

**Comment by Laegel** [comment]
For now, a link to CoC appears here: https://tauri.netlify.app/docs/about/governance#code-of-conduct

I'm just moving this issue to the next milestone.

**Comment by lorenzolewis** [comment]
Closing as this is covered in https://tauri.studio/v1/about/governance#code-of-conduct
