### ISSUE TITLE
[docs] Missing `require_literal_leading_dot` documentation

### ISSUE THREAD

**Issue by tweidinger** [tauri-apps/tauri-docs#1300]
The newly (`1.4.x`) introduced configuration switch `require_literal_leading_dot` which configures part of the `fs` scope is not properly documented yet.

Looping in @lucasfernog as discussed.

**Comment by amrbashir** [comment]
Should this be moved into `tauri-docs` repo instead?

**Comment by FabianLars** [comment]
yeah, let's do that, the schema itself looks correct as far as i can see.
