### ISSUE TITLE
Troubleshooting - blank page in built app context

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#133]
Build resulting in a blank page with the following backtrace:

thread '<unnamed>' panicked at 'Could not read asset tauri/build/index.tauri.html', .cargo/registry/src/github.com-1ecc6299db9ec823/tauri-0.9.2/src/server.rs:13:25
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: tauri::server::asset_response::{{closure}}
   9: tauri::server::asset_response

Solution might be to clean Yarn/NPM cache, reinstall and rebuild.

**Comment by lorenzolewis** [comment]
@Laegel is this for a potential FAQ or can we close this one?
