### ISSUE TITLE
Migrate to Docusaurus builtin i18n

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#143]
Since Docusaurus V2 has now a builtin support for i18n, it's better to use this system.
We also need to check the way its interact with Crowdin.

https://github.com/facebook/docusaurus/pull/3325

**Comment by lorenzolewis** [comment]
I'll add this one to my roadmap to work on
Adding link here for future reference: https://docusaurus.io/docs/i18n/tutorial

**Comment by lorenzolewis** [comment]
Closed by https://github.com/tauri-apps/tauri-docs/pull/607
