### ISSUE TITLE
Guide to manually create a Tauri project

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#1462]
Add to https://beta.tauri.app/2/guide/create/ (although it could be split into it's own page depending on how long it is).

**Comment by simonhyll** [comment]
Need to verify the linked PR's contents hasn't gotten lost somewhere in my restructuring, because I can't find the contents anymore.

**Comment by vasfvitor** [comment]
It should be in https://beta.tauri.app/start/create-project/ but now it's gone

**Comment by Rigidity** [comment]
Interested in picking this up, I'll move the content back into the page
