### ISSUE TITLE
Write Build & Distribute Guide(s)

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#1471]
Potentially could be under the same section since code signing and distribution are so closely linked to distribution. 

https://beta.tauri.app/2/guide/build/ and https://beta.tauri.app/2/guide/distribute/

Covers content here: https://tauri.app/v1/guides/building/ and here https://tauri.app/v1/guides/distribution/publishing (plus all the sibling pages on the sidebar)

**Comment by simonhyll** [comment]
Superseded by other issues, closing.
