### ISSUE TITLE
Validation App from Tauri homepage doesn't open on MacOS without ctrl-click

### ISSUE THREAD

**Issue by jmrossy** [tauri-apps/tauri-docs#148]
**Describe the bug**
The example [validation app](https://github.com/tauri-apps/tauri/releases/download/0.5.2-binaries/app.dmg) from the homepage top banner doesn't open on Mac. MacOs rejects it because it isn't signed.

**To Reproduce**
1. Go to https://tauri.studio/en/partners
2. Click on macOS - Dmg link on top banner
3. Install app
4. Try to launch app

**Expected behavior**
Launches

**Platform and Versions (please complete the following information):**

OS: MacOS
Node: -
NPM: -
Yarn: -
Rustc: -

**Comment by nothingismagick** [comment]
Regarding the code-signing, I think that we should have that done (and configurable) within the github action

**Comment by Laegel** [comment]
@nothingismagick For 2: I think we'll need to get Tauri's latest tag on the docs website, anyway. Doing this would allow us to create built apps links automatically (if we build each time there's a new release, of course).
To get the latest tag, we can either inject a new environment variable (I guess the current action that rebuilds the docs would perfectly fit), consumed when building the docs or fetching the latest tags with an HTTP request when browsing the docs (a bit like the "Release notes") but the latter would be less optimized.

**Comment by jbolda** [comment]
How do we want to version (if at all) the validation app? it doesn't exactly track 1-to-1 with `tauri.js`, does it? Since other deps could affect it as well.

**Comment by nothingismagick** [comment]
update on every core / tauri.js change?

**Comment by lucasfernog** [comment]
every core release should have the validation app on the Github release assets. But that will be tricky since I believe we don't have a certificate for code signing / notarization on macOS?

**Comment by nothingismagick** [comment]
I will sponsor this certification process from Apple Developer. Might take a few days to get it all sorted out though, and I am not sure yet WHICH company will be registered, there are a couple options... Lets discuss this in #core

**Comment by jbolda** [comment]
For the "version" of the app, should we adopt the tauri core version number then? As tauri.js will mostly be a light wrapper, it seems fine to mirror the core version.
