### ISSUE TITLE
Github PR & Issues Template 🐛

### ISSUE THREAD

**Issue by dreyfus92** [tauri-apps/tauri-docs#1500]
It would be nice to have templates for PRs and Issues, e.g.

![image](https://github.com/tauri-apps/tauri-docs/assets/85648028/f4c5f6d2-747c-4d8d-b2c3-761b4925dc92)

**Comment by lorenzolewis** [comment]
Really good point, thank you for this! I added it to the 2.0 milestone.

If you wanted to PR this then I'd be happy to accept it. Otherwise we can get this one added in on the pathway to 2.0.

**Comment by FabianLars** [comment]
( https://github.com/tauri-apps/tauri-docs/issues/1075 )

**Comment by lorenzolewis** [comment]
I guess this is double needed 😅 but on the bright side we can close two issues with one merge 😉

Thanks for always being vigilant @FabianLars

**Comment by lorenzolewis** [comment]
Closed by #1509
