### ISSUE TITLE
Add CrabNebula sponsor logo

### ISSUE THREAD

**Issue by Beanow** [tauri-apps/tauri-docs#1517]
CrabNebula requested the logo be placed.

They're a *Premium Sponsor*
URL: https://crabnebula.dev/
Here is their press kit: https://crabnebula.dev/press

## Board Decision

Since there was uncertainty around what "premium" entails, and how to base this on FTEs the @tauri-apps/tauri-board convened and decided the following:
1. The Tauri Board attests that CrabNebula has in the past months, and continues to sponsor, multiple FTEs worth of time to be spent on Tauri's priorities, as one of several contributions.
2. In the Board's opinion we find that CrabNebula meets and exceeds the existing norms for a "Premium Sponsor" and recommends that CrabNebula be recognized at least as a "Premium Sponsor".

NOT included in this decision:
- This does not include the previously-discussed adjustment of sponsorship/partner tiers, trademark usage, service partners, representative, security team, or any additional conversation points related to these topics (although this does not mean they are out of scope for further conversations, discussions, and proposals)

**Comment by lorenzolewis** [comment]
Thanks @Beanow ! I'll get a PR opened for this. I do know CrabNebula wants to time this announcement with a larger refresh so might wait to merge until they give the thumbs-up (I'll note it in the PR)

**Comment by simonhyll** [comment]
Gonna need a new PR for this one, I did an oopsie 😅
