### ISSUE TITLE
Feat: OG social image preview

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#1523]
For all of our pages we don't (yet) have a social image preview. We should make something awesome! Just something based off of current branding for now until if/when we do a larger brand refresh.

**Comment by JonasKruckenberg** [comment]
https://github.com/JonasKruckenberg/JonasKruckenberg/blob/main/src/pages/social-image/%5B...path%5D.png.ts

**Comment by lorenzolewis** [comment]
I did a bit of research and digging around on this. We can't yet add dynamic things to the starlight integration as the layout which contains the head element isn't exposed. https://github.com/withastro/starlight/issues/415 is probably what would enable this, allowing custom components overrides which we could then do in the head. 

I'm thinking for now we just add a static image to get a nice preview (which we can do with functionality available now) and put this on the to-do list for feature enhancements once that upstream issue is addressed.

**Comment by lorenzolewis** [comment]
Closed with #1525 , tracking dynamic OG image in #1344
