### ISSUE TITLE
cocoapods had to be manually installed for iOS to work

### ISSUE THREAD

**Issue by simonhyll** [tauri-apps/tauri-docs#1538]
### 📋 Page(s) affected (or suggested, for new content)

https://beta.tauri.app/2/guide/prerequisites/#ios

### 📋 Description or bullet point outline (if proposing new content)

We should probably add something like this to the steps:
https://stackoverflow.com/questions/20755044/how-do-i-install-cocoapods

Ran on a (mostly) fresh Mac and `tauri ios init` errors out unless you manually install cocoapods since it requires sudo

Alternative solution: make an upstream issue regarding the error so that `tauri ios init` will request sudo when necessary

**Comment by lorenzolewis** [comment]
Also needs to have `brew` installed it looks like.
