### ISSUE TITLE
[docs] Is there a way to set an application name that contains spaces?

### ISSUE THREAD

**Issue by mihai-dinculescu** [tauri-apps/tauri-docs#154]
Is there a way to set an application name that contains spaces?

As far as I can see, the application name, and subsequently the folder in which the application will be installed, is configured by the name property from Cargo.toml. This is very limiting, as it doesn't allow spaces, and results in ugly application names.

**Comment by corquaid** [comment]
would also like to know if this is possible.

**Comment by FabianLars** [comment]
I think [productName in tauri.conf.json](https://tauri.studio/docs/api/config#package.productName) allows using spaces too and converts it automatically in places where spaces are not allowed. I'm not 100% sure tho.

**Comment by corquaid** [comment]
> I think [productName in tauri.conf.json](https://tauri.studio/docs/api/config#package.productName) allows using spaces too and converts it automatically in places where spaces are not allowed. I'm not 100% sure tho.

But the `package > productName` in `tauri.conf.json` doesn't affect the app name in the Menu Bar on macOS - that's only controlled by `Cargo.toml`. Unless I'm misunderstanding how it works.

**Comment by FabianLars** [comment]
Hmm no, afaik it's supposed to use the productName (with Cargo.toml = fallback) as CFBundleName in the plist file of the .app bundle (cfbundlename is what's used in the menu bar)

**Comment by AdrianVispalia** [comment]
> I think [productName in tauri.conf.json](https://tauri.studio/docs/api/config#package.productName) allows using spaces too and converts it automatically in places where spaces are not allowed. I'm not 100% sure tho.

You also need to add the escape sequence, I believe. I was getting errors when building with a productName with spaces. Now I have this:
```json
  "productName": "PC\\ Fix\\ Guide",
```

**Comment by matthewCmatt** [comment]
> But the `package > productName` in `tauri.conf.json` doesn't affect the app name in the Menu Bar on macOS - that's only controlled by `Cargo.toml`. Unless I'm misunderstanding how it works.

I believe this is set by the WindowConfig's `title` field https://v2.tauri.app/reference/config/#title-1

Edit: This is completely wrong, the menu bar name should use the `productName` Tauri config.

**Comment by SteveChurch** [comment]
> > But the `package > productName` in `tauri.conf.json` doesn't affect the app name in the Menu Bar on macOS - that's only controlled by `Cargo.toml`. Unless I'm misunderstanding how it works.
> 
> I believe this is set by the WindowConfig's `title` field https://v2.tauri.app/reference/config/#title-1

I'm not so sure, when running `dev` no matter what is placed in `productName` within the `tauri.conf.json` it still uses what is found within `Cargo.toml` - Seemingly the `title` within mine also does nothing, or at least nothing I can tell visibly. 

EDIT: I now see `packageName` showing within the `About N` menu. But the application itself does seem to rely on the `Cargo.toml -> name`

**Comment by matthewCmatt** [comment]
> I'm not so sure, when running `dev` no matter what is placed in `productName` within the `tauri.conf.json` it still uses what is found within `Cargo.toml` - Seemingly the `title` within mine also does nothing, or at least nothing I can tell visibly.
> 
> EDIT: I now see `packageName` showing within the `About N` menu. But the application itself does seem to rely on the `Cargo.toml -> name`

Interesting, this doesn't match my behavior on Tauri v1.1.1. This sounds like a bug. If you can create a reproduction repo, this could be filed as a bug.

**Comment by FabianLars** [comment]
If "the application itself..." means the actual binary then that's intentional. In v2 the binary now keeps the Cargo.toml name or the `mainBinaryName` config from tauri.conf.json
