### ISSUE TITLE
Add guides or templates on how to publish to popular app stores

### ISSUE THREAD

**Issue by Benji377** [tauri-apps/tauri-docs#1550]
### 📋 Explain your issue

Tauri is an interesting framework, as it seemingly connects two different programming languages (JavaScript and Rust). The issue is that this is very uncommon, and a lot of external tools and frameworks don't have dedicated guides or instructions on how to set them up with Tauri. Some of those are app stores, which are a great tool to spread awareness of your app, find new users and maybe potential contributors. 

I am currently developing an antivirus using Tauri and Next.js. It currently has a decent amount of users and after just a couple of days, someone suggested publishing the app to Flathub and soon others followed with suggesting other app stores like Snapcraft or AppImageHub and Chocolatey. I did some research and tried to set them up, here are my results so far:

- Chocolatey: Uploaded executable using [this guide](https://dev.to/tgotwig/publish-a-simple-executable-from-rust-on-chocolatey-2pbl). Executable got flagged as malware and still awaiting moderators approval
- Flathub: Unclear requirements and open discussion about Tauri having [issues](https://github.com/tauri-apps/tauri/discussions/4426) stopped me from trying it any further
- Snapcraft: Really hard to set up, still testing. I am currently at more than 100 failed attempts
- AppImage: A known bug prevents it from being uploaded: https://github.com/tauri-apps/tauri/issues/7736

I am sure if you are smart enough you are able to figure it out eventually, but for me, it's just very complicated to understand. I will keep on trying and see if I am able to achieve anything. If I do, I will try to remember to report back here.

**Comment by simonhyll** [comment]
We'll be covering this in a Distribute section. Tracking for 2.0.

**Comment by Benji377** [comment]
Thank you simon. I also have an update: I managed to publish my app on snapcraft

**Comment by lorenzolewis** [comment]
@Benji377 if you're interested in contributing a guide on any of these we'd love to have them! This would be the first guide in this area for the new Docs 2.0 effort so there may be a chunk of work on crafting the copy, but if there are any steps, observations, or notes you'd like to share we'd love to have them!

**Comment by Benji377** [comment]
My approach to creating a snap looked something like this:
- Take a basic template for Rust snap
- Add/Change a line
- Commit the file to GitHub
- Wait for the Snapcraft dashboard to pick it
- Wait for the Build process to fail
- Start again

For AppImage, I tested it, and it runs fine on Debian WSL2. Then the workflow failed when publishing it to the [AppImage repository](https://github.com/AppImage) and with the help of another user that discovered the [issue](https://github.com/tauri-apps/tauri/issues/7736) I created a PR to somewhat fix it: https://github.com/tauri-apps/tauri/pull/7843

For Chocolatey, I basically removed all the PowerShell scripts to avoid having to write any install or setup steps, and it magically worked. Then the executable got flagged as malware, probably because I forgot to sign it. 

All I am saying is that I would really like to write guides on this for Tauri, I love contributing to this project, but my methods of reaching the goal are not very professional and might not be suitable for other applications/projects

**Comment by simonhyll** [comment]
> but my methods of reaching the goal are not very professional

@Benji377 don't worry about that at all, if you throw something together based on your working approach we can look into it together to make it professional 🙂

**Comment by Benji377** [comment]
Ok sure then. Where should I write it? Should I open a PR?

**Comment by simonhyll** [comment]
@Benji377 Sorry for slow reply, been very busy. You can write it as a sub article for the deployment guide perhaps? We're still figuring out the exact formatting of the guides, gotta wait for Lorenzo to get back from his vacation before we do too big changes to that part. But if you write an article somewhere in the docs we can worry about exact placement and changing formatting later, just try to get all the information into a markdown file and we'll figure out where it should go later. 😄

**Comment by Benji377** [comment]
No worries, I had a lot to do for university too. I finally wrote a rough outline together and opened a PR

**Comment by tweidinger** [comment]
I think we can close this as completed since we have snap and flatpak docs for the packaging and guides for popular stores with the recent PRs from lucas. https://v2.tauri.app/distribute/
