### ISSUE TITLE
Russian language localization request

### ISSUE THREAD

**Issue by paranoidPhantom** [tauri-apps/tauri-docs#1561]
### 📋 Explain your issue

Would like to request Russian language to be added to the localization list, would like to translate the docs in to Russian.

**Comment by lorenzolewis** [comment]
Hi there! Thanks for putting this in! I put together a meta-issue to track this in #1611 and tagged you for Russian there. I'm going to go ahead and close this so that we can track any language proposals all in the same place in #1611
