### ISSUE TITLE
[docs] Changes to Tauri-Electron comparison list

### ISSUE THREAD

**Issue by aleksey-hoffman** [tauri-apps/tauri-docs#159]
Hey guys, I just discovered Tauri, and I already love it, great job!
However I think that the feature comparison list needs some work. It needs more of useful information and less of weird information on it.

Now, let's break down some of the metrics on the comparison list:

## 1. Can Render PDF (Tauri: yes; Electron: no)
If by "rendering" you mean "displaying PDFs", then the comparison is false, it's actually very easy to do in Electron:

### Electron 10.1.3: `mainProcess.js`
```
function openPDF () {
  let pdfWindow = new BrowserWindow({
    width: 1280,
    height: 720,
    webPreferences: {
      plugins: true
    }
  })

  pdfWindow.loadURL('file://C:/test/test.pdf')
}
```
Plus, neither Tauri nor Electron were created specifically for making "PDF reader" apps, so the ability to "render PDFs" is not really a main feature of either of them.

## 2. Multithreading (Tauri: yes; Electron: no)
Multithreading is an ability to run multiple blocking tasks concurrently. And we all know that Electron has multiple ways of achieving this:

- Web worker
- Node worker_threads
- Spawning separate node processes
- Executing binary files via system terminal

Which, again, means that the comparison is factually false. I would argue it's even easier to utilize all the threads of your CPU with Electron because creating a worker.js and a message event listener is much easier than creating a proper multithreading system on Rust.

## 3. Splashscreen (Tauri: yes; Electron: yes)
This comparison doesn't even make any sense. The Nokia 3310 had a splashscreen animation. Splashscreen is just a loading screen, which can be done on anything that runs code. You can even do it with pure HTML without any scripting.

Am I missing something or does this comparison convey absolutely no meaningful information? It's like saying that both Tauri and Electron require a computer to run and can both perform computations. Don't you say! Incredible, that! 😄

## 4. Speed

I was quite impressed by the ~0.5 sec launch speed of my test Tauri app.

Guys, why would you compare the ability to "Render PDF" and "To have a Splashscreen" but not speed - one of the most important metrics to devs and users? The app launching speed, the computational speed of different tasks (Rust vs V8), the compilation speed, etc.

## 5.  Interface Service Provider (Tauri: Varies; Electron: Chromium)

This comparison, unfortunately, doesn't convey any useful information either. 

How does it all work? How is it possible that we can use Node's npm packages on Rust? Can I just install `node` bin module from npm and run ALL Node's modules on Rust? What kind of black magic is this?

We know that Electron supports image, audio, video decoding, it gives us the browser `window` and `document` objects that have different listeners (click, scroll, drag, etc), it supports the majority of HTML / CSS / JS features, and so on. But it's not clear how Tauri handles all of this. Does everything just works the same? Or do we have to create our own low-level listeners in Rust, or what?

What HTML / CSS / JS features do we lose with Tauri? 

## 6. Supported file types

I can see that Tauri can decode and display some types of images, but why can't it decode and display videos at all? What file types will be supported in the future? 

Why is "supported file types" metric not on the comparison list? This sort of information would actually be useful to have on the comparison list.

**Comment by nklayman** [comment]
I apologize for the long delay here, just waiting for the custom protocol to be all ready before doing the performance benchmarks.

**Comment by nklayman** [comment]
PR merged :tada:
