### ISSUE TITLE
404 in next docs

### ISSUE THREAD

**Issue by codingedgar** [tauri-apps/tauri-docs#1592]
### 📋 Page(s) affected (or suggested, for new content)

https://beta.tauri.app/blog/tauri-mobile-alpha/beta.tauri.app 

### 📋 Description or bullet point outline (if proposing new content)

hi, https://beta.tauri.app/blog/tauri-mobile-alpha/ points to https://beta.tauri.app/blog/tauri-mobile-alpha/beta.tauri.app which returns 404

**Comment by FabianLars** [comment]
Thanks, fixed it :)
