### ISSUE TITLE
Decision about the docs

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#16]
@tauri-apps/core 

The current docs are using Docusaurus V1.14.4 that supports i18n, a required feature.
Docusaurus V2 is still in alpha stage and does not support i18n yet. But, as Jacob told me, it's the next big thing they'll add in V2. 
At first, I was thinking about waiting for V2 to support i18n to eventually switch to it but I changed my mind, as we have been recommended to start with V2 by Docusaurus team members. But since this decision isn't mine alone:

- Should we stick to V1? 
This choice would be the best for stability, already setup. 
- Should we switch to V2?
V2 has many interesting features that V1 will never have (theme switch, better templates customization, plugins and better extensibility [like CSS preprocessors]).

If you need to make a choice by seeing what are the differences between the two versions, here is V1: https://docusaurus.io/en/ and here is V2: https://v2.docusaurus.io/

Waiting for your comments!

**Comment by nklayman** [comment]
I think it mostly depends on whether or not we want to add translations right away. IMO we should wait till beta/RC to add translations as the docs are changing really fast now and we don't want to burn out our translators. We also don't have support capabilities for languages other than English so we may struggle to help people who don't speak English.

**Comment by nothingismagick** [comment]
I think Noah is right here. I mean if v2 at some point this summer offers the i18n engine - and we can stomach the `alpha` badge - then let's follow the Docusaurus team advice.

**Comment by jbolda** [comment]
Sounds like lots of similar thoughts. We didn't want to make a decision without getting more input from everyone. The timeline that we have for the docs seems that starting on v2 makes a lot of sense for the better templates and scss support.

Thanks to @jsjoeio for the extra insight. I reached out to them for their opinions as well.

**Comment by Laegel** [comment]
All right. Unless someone has anything to say against this decision, I'll start working on V2 and move all the V1 stuff to the V2 and try to deploy a version (thanks to @jbolda !) before this week-end.
