### ISSUE TITLE
White GitHub logo on the navbar becomes invisible on light theme

### ISSUE THREAD

**Issue by bobaekang** [tauri-apps/tauri-docs#162]
Thanks for working on a great project.

I just noticed that switching to the light theme makes the white GitHub logo on the navbar invisible against the white background. See the screenshots below:

**On dark theme**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/22449454/108537150-e2c8a200-72a2-11eb-9673-bcf01a9539d7.png">

**On light theme**
<img width="412" alt="image" src="https://user-images.githubusercontent.com/22449454/108537177-ebb97380-72a2-11eb-8172-a2b548c72c29.png">

Please change the GitHub logo SVG when switching themes to keep it visible. Thank you!

**Comment by nothingismagick** [comment]
Oh wow - thanks for the headsup! Maybe the quick fix is to give the logo a background color the same as the dark header bar.

**Comment by Laegel** [comment]
Whoopsie, I forgot that.Thanks @bobaekang !
