### ISSUE TITLE
Hosted fonts

### ISSUE THREAD

**Issue by surendrajat** [tauri-apps/tauri-docs#165]
Hi. My tracker-blocker is blocking `https://fonts.googleapis.com/css?family=Tauri&display=swap` and the page doesn't look so good without it. Could you please host this font with other static stuff?

**Comment by Laegel** [comment]
Hey @Surendrajat ! Thanks for your issue, we'll consider another solution for the fonts.

**Comment by bobaekang** [comment]
@Laegel Using fontsource would be a good option to address this. See [here](https://github.com/fontsource/fontsource/tree/master/packages/tauri).

**Comment by Laegel** [comment]
Thanks @bobaekang , that's definitely an interesting repo I didn't know about!

**Comment by surendrajat** [comment]
Thanks @Laegel, for the quick fix. Works well.
