### ISSUE TITLE
[docs] Remove `libvips` from Arch Linux dependencies 

### ISSUE THREAD

**Issue by loziniak** [tauri-apps/tauri-docs#1663]
tauri-apps/tauri#2150 seems to be no more relevant, I don't have `libvips` in my system and I ran `npm i -D @tauri-apps/cli` in an empty folder without problems.

```
$ uname -a
Linux latitude5580 6.4.6-3-rt8-MANJARO tauri-apps/tauri#1 SMP PREEMPT_RT Thu Aug  3 19:14:02 UTC 2023 x86_64 GNU/Linux
```

**Comment by naman-crabnebula** [comment]
Yeah, I can confirm this. Uninstalling `libvips` did not affect any Tauri app ( I am using Arch Linux as well )

Also, we don't ship `libvips` in AppImage, and didn't face any issue either. Also, as per best of my knowledge, we don't even use `libvips` bindings. ( They have only C/C++/shell script bindings )

So, I guess it is safe to remove `libvips` from Arch Linux Dependencies.
