### ISSUE TITLE
I'm trying to run tauri for android

### ISSUE THREAD

**Issue by DIMFLIX** [tauri-apps/tauri-docs#1671]
### 📋 Page(s) affected (or suggested, for new content)

https://beta.tauri.app/guides/prerequisites/#configure-for-mobile-targets

### 📋 Description or bullet point outline (if proposing new content)

I have executed all the commands from the documentation (https://beta.tauri.app/guides/prerequisites/#configure-for-mobile-targets ), I'm trying to run `pnpm run tauri android dev` and get a huge error
[err.txt](https://github.com/tauri-apps/tauri-docs/files/13321384/err.txt)

I ask for help! It is very urgent to make an application for Android.
The configuration was chosen by (pnpm, vanilla, typescript)

**Comment by FabianLars** [comment]
You didn't answer me on discord :(

Did you also follow this guide? https://beta.tauri.app/guides/create/mobile/

**Comment by FabianLars** [comment]
Or different question: How did you set up your app? I assumed you tried to convert a v1 app or something.

**Comment by DIMFLIX** [comment]
> Or different question: How did you set up your app? I assumed you tried to convert a v1 app or something.

Here are all my installation steps:
I have installed android studio
Installed JAVA_HOME ANDROID_HOME SDK_HOME environment variables

Then I created a project (pnpm, Vanilla (HTML, CSS, JS), typescript)

pnpm create tauri-app --alpha
cd myapp
pnpm i
pnpm run tauri android dev

**Comment by DIMFLIX** [comment]
> Or different question: How did you set up your app? I assumed you tried to convert a v1 app or something.

Now there is a completely different problem. The last one disappeared for some reason. See here on github in this question

**Comment by FabianLars** [comment]
Ah apologies, i didn't notice the different error.

Could you also post the output of `pnpm tauri info` please?

Also, i would suspect that the issue is the cyrillic characters in the path (`шлагбаум`) - could you try changing that to ascii/english characters and try again?

Not exactly sure if that's our fault or lld's or rust's 🤔

**Comment by DIMFLIX** [comment]
> Ah apologies, i didn't notice the different error.
> 
> Could you also post the output of `pnpm tauri info` please?
> 
> Also, i would suspect that the issue is the cyrillic characters in the path (`шлагбаум`) - could you try changing that to ascii/english characters and try again?
> 
> Not exactly sure if that's our fault or lld's or rust's 🤔

PS C:\Users\dimflix\Documents\MyProjects\шлагбаум\myapp> pnpm tauri info

> myapp@0.0.0 tauri C:\Users\dimflix\Documents\MyProjects\шлагбаум\myapp
> tauri "info"


[✔] Environment
    - OS: Windows 10.0.22621 X64
    ✔ WebView2: 119.0.2151.44
    ✔ MSVC: Visual Studio Build Tools 2022
    ✔ rustc: 1.75.0-nightly (0f44eb32f 2023-11-09)
    ✔ cargo: 1.75.0-nightly (7046d992f 2023-11-08)
    ✔ rustup: 1.26.0 (5af9b9484 2023-04-05)
    ✔ Rust toolchain: nightly-x86_64-pc-windows-msvc (default)
    - node: 20.9.0
    - pnpm: 8.10.2
    - npm: 10.1.0

[-] Packages
    - tauri [RUST]: 2.0.0-alpha.17
    - tauri-build [RUST]: 2.0.0-alpha.11
    - wry [RUST]: 0.34.2
    - tao [RUST]: 0.23.0
    - tauri-cli [RUST]: 2.0.0-alpha.17
    - @tauri-apps/api [NPM]: 2.0.0-alpha.11
    - @tauri-apps/cli [NPM]: 2.0.0-alpha.17

[-] App
    - build-type: bundle
    - CSP: unset
    - distDir: ../dist
    - devPath: http://localhost:1420/
    - bundler: Vite

**Comment by DIMFLIX** [comment]
> Also, i would suspect that the issue is the cyrillic characters in the path (`шлагбаум`) - could you try changing that to ascii/english characters and try again?

Now, I'm trying

**Comment by DIMFLIX** [comment]
> Ah apologies, i didn't notice the different error.
> 
> Could you also post the output of `pnpm tauri info` please?
> 
> Also, i would suspect that the issue is the cyrillic characters in the path (`шлагбаум`) - could you try changing that to ascii/english characters and try again?
> 
> Not exactly sure if that's our fault or lld's or rust's 🤔


OK, everything went further, but an error came out again. Already another
![image](https://github.com/tauri-apps/tauri-docs/assets/112165977/00113af3-0e02-4e5a-99df-96658f71f644)

**Comment by DIMFLIX** [comment]
@FabianLars please help me!!

**Comment by FabianLars** [comment]
Can you delete the `gen/` folder and run `pnpm tauri android init` again?
