### ISSUE TITLE
Add Rust debugging instructions

### ISSUE THREAD

**Issue by MRobertEvers** [tauri-apps/tauri-docs#169]
**Is your feature request related to a problem? Please describe.**
A debugger cannot translate bundled js back to source files. The 'debug' section of the website only describes how to debug via print statements. However, I think `tauri` could gain more mainstream popularity if users were able to use a debugger on both the rust code and the JS code. (The rust code is easy to attach a debugger already)

**Describe the solution you'd like**
The packager/bundler (I believe this is https://github.com/tauri-apps/tauri-inliner) should optionally generate a sourcemap. This will allow debuggers to attach to the webview and allow users to step through their JS code.

Here are the sourcemap options https://www.npmjs.com/package/uglify-js#source-map-options
```
var result = UglifyJS.minify({"file1.js": "var a = function() {};"}, {
    sourceMap: {
        filename: "out.js",
        url: "out.js.map"
    }
});
```

I will test this out myself in the next few days.

**Comment by nklayman** [comment]
I've renamed and moved this issue as per the new direction it has taken. Also, we've recently completely removed the inliner, so the original issue shouldn't be present any more.
