### ISSUE TITLE
Requested translations languages

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#177]
Spanish, Italian, Japanese and German languages added by request of translators.

**Comment by natastro** [comment]
Hello! I'd love to help with Spanish translations if needed. Thank you!

**Comment by Laegel** [comment]
Hey @natastro ! Thanks for your proposal. We first need to release Tauri's Beta RC with updated docs, then we'll enable these new languages in Crowdin. We'll let you know when we're ready for the next steps. :D

**Comment by lorenzolewis** [comment]
Closing this as we've now launched the Crowdin integration. Translations can be done at https://tauri.crowdin.com/documentation
