### ISSUE TITLE
New: Starting a new project docs page

### ISSUE THREAD

**Issue by jensim** [tauri-apps/tauri-docs#180]
There is no page for stating a new tauri project, but 4 pages on retrofitting it into an existing one.

If we want tauri to be a thing, we need a community, and to have that we need to be welcoming, in spirit, code, and docs. The docs is where people end up who have seen the first youtube intro, and want to get started coding. Lets not loose our potential new community members in the menu.

I move, we should add a menu for `Starting a project` (from scratch), and group the `Retrofit existing project` pages into a menu group named `Add to project`.

When I started out looking at Tauri a month or so back, I was nearly overcome with how difficult it seemed to start out, using the docs. I was only when i had created an entire project by hand and retrofitted it with Tauri using the docs that I navigated to the `Vue CLI Plugin Tauri` by change. And it turned out to be a great starting point for a new project. No indication from the docs though.

**Comment by Laegel** [comment]
Hey @jensim , thanks for your feedback!

This is the first time I hear the docs are hard to get into, I apologize for this difficulty. The goal was indeed to make it as simple as possible with the smoothest experience possible, by ensuring any people coming from Rust or JS world is able to use Tauri thanks to an explicit documentation.
I'll review your PR ASAP!

**Comment by nothingismagick** [comment]
FYI - @nklayman mentioned that you should actually have PR'd against the `feat/beta-rc-update` branch, not `dev`.

**Comment by jensim** [comment]
Beta has landed, and I ported my changes to a new branch based on dev here: #185

**Comment by Laegel** [comment]
Hey @jensim , let us know if you could use some help!

**Comment by jensim** [comment]
Thanks @Laegel 🥳👍🏻
Im balancing time shortage against multiple OSS engagements 
This is first among the ones I dont own myself

If im too slow, this could be up for grabs
I need to learn more about Tauri in order to do this I think 🤷
But if we are not in a hurry, or this is not in line for prio, I'll be picking it up when I have learned more

Thanks for being so supportive and welcoming 😊

**Comment by lorenzolewis** [comment]
Closing this out as we've been revamping our guides and I believe this is covered now.
