### ISSUE TITLE
Migrate the "Debugging in CLion" guide to RustRover

### ISSUE THREAD

**Issue by bravit** [tauri-apps/tauri-docs#1800]
### 📋 Page(s) affected (or suggested, for new content)

https://tauri.app/v1/guides/debugging/clion

### 📋 Description or bullet point outline (if proposing new content)

Given that [RustRover](https://www.jetbrains.com/rust/) is the dedicated Rust IDE by JetBrains, it makes sense to migrate the "Debugging in CLion" guide to RustRover. 

Suggested changes:
* Changing the title and the link
* Cleaning wording about Cargo workspace creation (it's already there for frontends in Rust, and it's not needed for other frontends) 
* Suggest running both `tauri-app` and the frontend development server via Run Configurations (RustRover provides full support for any of yarn, npm, pnpm, etc.)
* Better wording regarding the actual dev server that should be run (the one mentioned in `beforeDevCommand` of `tauri.conf.json`) 
* Adding tips and screenshots illustrating actual debugging experience. 

I volunteer to rewrite the guide in both the `v1` and `v2` branches. WDYT?

**Comment by FabianLars** [comment]
Yes, awesome idea! Contributions are very welcome :)
