### ISSUE TITLE
Retrieve docs from the Wiki

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#19]
All docs from the current Wiki should be moved to the website. Also, we need to ensure that every links are updated.
Contents may have to be updated, reworked and detailed.

**Comment by nothingismagick** [comment]
do we want to retire the wiki?

**Comment by Laegel** [comment]
IMO, it's no use to keep both. The goal of the Docusaurus was to merge the Wiki to the actual tauri.studio content, wasn't it?

**Comment by nothingismagick** [comment]
Yes - I totally agree. It just wasn't clear from the issue topic. Great!

**Comment by Laegel** [comment]
Right, I've moved the Wiki pages to the website. They need improvements but it can be done in a second time.
