### ISSUE TITLE
[docs] Command K does not work on MacOS + Firefox

### ISSUE THREAD

**Issue by elibroftw** [tauri-apps/tauri-docs#1904]
Command + K does not open search box on macOS Firefox. This is a docs problem since https://mantine.dev/ works fine.

**Comment by amrbashir** [comment]
I believe this is on https://beta.tauri.app right?

**Comment by elibroftw** [comment]
No. I experienced the issue on tauri.app. not sure if it effects beta.tauri.app

**Comment by amrbashir** [comment]
`Ctrl + K` works for me on Windows, can't test on macOS though but I think it is probably because of https://github.com/tauri-apps/meilisearch-docsearch/blob/dev/src/DocSearch.tsx#L36 although we trat `ctrl` as command on macOS here https://github.com/tauri-apps/meilisearch-docsearch/blob/1ba6f8ffb73d9fea449db126736696a06bacef2a/src/useDocSearchHotKeys.ts#L56-L58

**Comment by simonhyll** [comment]
On the old site `CMD + K` doesn't open search. It does work however on the new site.

I think we should close this as not gonna fix, really not interested in fixing the old site, especially not when this is something that's fixed in the new site.

**Comment by FabianLars** [comment]
If we end up switching the new site to meilisearch back from whatever it's using now then this will also be a problem on the new site. If we're _sure_ this won't happen then i agree with the wontfix.
Edit: At least wontfix in the context of this repo. If we support meilisearch-docsearch outside of it then ignore that.

**Comment by amrbashir** [comment]
I am not sure how customizable the new site search bar or if you intend to switch to meilisearch-docsearch (I will let you be the judge of that) but `Command/Ctrl + K` is a common hotkey especially for those users coming from a JS background where algolia search and its docsearch component is widely used.

Also note that the new site search only supports `/` as a hotkey while meilisearch-docsearch supports `Command/Ctrl+K`, `/` and `s` by default. It also will start the search with the current highlighted text if any. I think these two features should be considered for the new site and try to be implemented upstream if possible or switch over to meilisearch-docsearch

**Comment by FabianLars** [comment]
just to be clear, the beta website currently does not use our meilisearch instance, it's some offline search thingy so switching to meilisearch-docsearch would not just be a frontend change.
