### ISSUE TITLE
wired result of `basename(file, extname(file))`

### ISSUE THREAD

**Issue by wsw0108** [tauri-apps/tauri-docs#1905]
use ext from call `extname` for `basename` return wired result:

``` javascript
const ext = await extname('some-json-file.json'); // 'json'
const nameNoExt = await basename('some-json-file.json', ext); // 'some--file.'
```

Maybe the correct usage is as below?:
```js
const ext = await extname('some-json-file.json'); // 'json'
const nameNoExt = await basename('some-json-file.json', '.' + ext); // some-json-file
```

**Comment by FabianLars** [comment]
Thanks for the report. I think this includes 2 action items.
1) Update the docs to be clear about the `.` requirement.
2) Change the implementation from the currently used replace to maybe something like [rsplit_once](https://doc.rust-lang.org/std/primitive.str.html#method.rsplit_once) to make sure we a) don't replace multiple occurences and b) make sure we replace the right most occurence.

**Comment by amrbashir** [comment]
the correct usage would be to add the dot e.g. `basename("path/to/file.json", ".json")` however the implementation has a bug as fabian mentioned and we should instead use `.strip_suffix()`, I will open PRs to fix this behavior

**Comment by amrbashir** [comment]
PRs for v1 https://github.com/tauri-apps/tauri/pull/9166 and v2 https://github.com/tauri-apps/tauri/pull/9165
