### ISSUE TITLE
Document .taurignore in develop section

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri-docs#1955]
> > This definitely needs to be documented for people using Rust workspace.
> 
> I agree but where would you expect to find this in the docs? Genuine question as we're currently rewriting the docs and i have no idea where to put this.

I would imagine a sub-section or a separate page under `develop` such as here:

https://beta.tauri.app/guides/develop/

Which is about the DX experience, including things like setting up IDEs for Tauri dev., where best to place shared env variables and keys, how to set up auto-reloads (where `.taurignore` fits), etc.

_Originally posted by @boan-anbo in https://github.com/tauri-apps/tauri/issues/4617#issuecomment-1992197832_

**Comment by roniemartinez** [comment]
As discussed in Discord, include the files that are recommended to be ignored such as `deny.toml` (see https://github.com/tauri-apps/tauri/issues/9258).
