### ISSUE TITLE
Need generator for CLI reference page

### ISSUE THREAD

**Issue by dklassic** [tauri-apps/tauri-docs#1985]
Need a generator for CLI reference pages to prevent missing commands. Currently CLI reference pages are static pages and will prone to error as Tauri updates.

**Comment by vasfvitor** [comment]
you mean the `cli.mdx` files in references? I just looked it at next and it seems they are not generate, am I missing something?

**Comment by FabianLars** [comment]
Ah that's my bad then, I thought we still autogen it like in the old docs

**Comment by dklassic** [comment]
No wonder why I can't find the autogen scripts ~ _ ~ 

Should we still do it in the autogen way somehow or should we just manually change the pages with #1936 and call it a day?

**Comment by vasfvitor** [comment]
This could be added to the plans yeah, right now the cli page is outdated, missing `tauri permission` commands and maybe more. For now I think it's good to just manually change

**Comment by vasfvitor** [comment]
maybe [clap markdown](https://crates.io/crates/clap-markdown) could be implemented upstream? But it doesn't seem to be maintained
