### ISSUE TITLE
Rework content in a user-friendly way

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#2]
Right now, the website only contains Docusaurus placeholders and raw ideas that need to be refined to be decent.

What needs to be displayed (unordered list):
- reasons to use Tauri;
- more about Tauri, philosophy (details about what matters most for us, like security);
- usage/setup;
- examples/recipes;
- API, both Rust and JS public interface;
- showcase, the awesome community made projects;
- sponsors & donations;
- useful links for community (GitHub, Twitter, Discord, Dev.to, Open Collective, Crowdin).

**Comment by nothingismagick** [comment]
I think that `more about Tauri` and `reasons to use tauri` should stay at https://tauri.studio - as should the `showcase`. These docs will be dense, and it will already be complex enough to navigate them.

**Comment by Laegel** [comment]
Since Docusaurus has a native Crowdin support, I was thinking about merging tauri.studio content into the new docs website.
Also, this way, examples, setup... anything that implies to show code that may change benefits from versioning.

**Comment by nothingismagick** [comment]
Hmm. Good point.
