### ISSUE TITLE
(next) Some of the documentation for the fs plug-in is incorrect

### ISSUE THREAD

**Issue by GuoJikun** [tauri-apps/tauri-docs#2006]
`fs:allow-app-meta-recursive` has the same description as `fs:allow-app-meta`.

![image](https://github.com/tauri-apps/tauri-docs/assets/21582741/fcc9fa64-25df-4277-9907-3b4158c06cae)

**Comment by vasfvitor** [comment]
https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/fs/permissions/autogenerated/reference.md

**Comment by vasfvitor** [comment]
on a note: we have a PR to automate the generation of the permission table #1890 by fetching from the generated file but it's pending i18n implementation. If wish and have any idea as how to implement i18n in a way that avoid translating and copying multiple times the same sentences, or maybe make the process less cumbersome, be welcome

**Comment by GuoJikun** [comment]
- Automatic translation
- Different files are referenced according to the locale
