### ISSUE TITLE
Book update

### ISSUE THREAD

**Issue by g-berthiaume** [tauri-apps/tauri-docs#205]
The official Tauri documentation [mentions](https://tauri.studio/en/docs/about/book) a book coming in "late 2020".
This kind of info is hard to maintain in docs, so I thought I would report it.

Looking forward to reading it !

**Comment by nothingismagick** [comment]
You are very right - that was planned before we all got hit with Covid fatigue. We anticipated hitting beta much sooner too, now that the beta & stable are just around the corner we will be getting back to this. Thanks for the reminder!

**Comment by g-berthiaume** [comment]
> You are very right - that was planned before we all got hit with Covid fatigue. 
I think we can all relate to that. Keep up the good work.

Merci et bonne journée.
