### ISSUE TITLE
KC of I'll be brr SF oGC cc cc fvh

### ISSUE THREAD

**Issue by drmason13** [tauri-apps/tauri-docs#206]

**Comment by nothingismagick** [comment]
An interesting proposition, to be sure. Not clear how to actually do such a thing, but I too hail our feline overlords.

**Comment by drmason13** [comment]
Sorry about this! I think I pocket-dialled github...

**Comment by nothingismagick** [comment]
glad it wasn't https://www.reddit.com/r/ihadastroke/
