### ISSUE TITLE
Add Bun to command groups and make casing consistent

### ISSUE THREAD

**Issue by Rigidity** [tauri-apps/tauri-docs#2183]
### Question you want answered

How do I install with Bun?

### Where did you look for an answer?

The docs only have yarn, npm, pnpm, and cargo. I also want to make the casing consistently lowercase for all commands in the command group.

### Are you willing to work on this yourself?

- [X] I want to work on this myself

**Comment by vasfvitor** [comment]
man I just saw this issue sorry I stepped on you at the time, I did glanced a discussion on discord about it but didn't noticed this issue, oh man... what I've done


closed by https://github.com/tauri-apps/tauri-docs/pull/2212
