### ISSUE TITLE
[docs] gettings started guide: how build my Tauri app

### ISSUE THREAD

**Issue by gabenddos** [tauri-apps/tauri-docs#2184]
### Question you want answered

After just creating my first Tauri App, what I need to know and how so I can build my Tauri App.

### Where did you look for an answer?

More specific, I've been testing the Tauri 2.0 beta on my personal Web App to try port it to Mobile and Desk native apps (.dmg .exe .apk, etc).
And, following the https://v2.tauri.app/start/create-project/ in the quick starts worked like a charm :rust: :tauri: :chad: 
Then the thing that interest me the most about the migration from an existing project to Tauri is how to build my app into the executables or installable bundles (.dmg, .exe, .apk, etc). So, the guide in the next steps suggested me this links which the Learn How to Build your Tauri app(img 1) was the most important for me. 

![image](https://github.com/tauri-apps/tauri-docs/assets/36337762/103ebc49-c1e2-4c26-80c0-b90028fb42bf)

But the page that it leads is empty currently. (img 2)
https://v2.tauri.app/develop/
![image](https://github.com/tauri-apps/tauri-docs/assets/36337762/1802fae3-fde6-415e-91a5-746b35ae70f9)

So I wanna fill this guide on how build my App

### Page URL

https://v2.tauri.app/start/create-project/#next-steps

### Additional context

I don't know if the current redirect that this link makes goes to the section that represents a Build guide. By **build** I mean Build and Deploy the executables .exe, .dmg or ios, etc, for the targeted platform that the developer needs to ship the app. So there are a few questions that need to be answered there.

### Are you willing to work on this yourself?

- [X] I want to work on this myself

### Checklist
- [ ] Prerequisites: e.g. to build your app you need to have a working app on development e.g. (getting started create a project) 
- [ ] CLI Commands to build App (include reference to the CLI reference docs)
- [ ] Building Tauri app for Windows
- [ ] Building Tauri app for Mac
- [ ] Building Tauri app for Linux
- [ ] Building Tauri app for Android
- [ ] Building Tauri app for iOS
- [ ] Other edge cases?
- [ ] Have a Next Steps section well defined

WIP: Next Steps Ex:
- [ ] Next Steps: Platform-specific configuration?
- [ ] Next Steps: DevOps integrations so the build is made automatically (link with custom docs with snippets and guide on how to CI/CD the builds with GitHub Actions.
- [ ] Next Steps: Common deployment cenários e.g. host the exe on a website. Or for example with Android. It's very common to publish your APK at Google Play. So the docs should at least mention that with the generated APK the developer has everything he needs to continue with the publishing process on PlayStore (maybe even provide some official Google link on how to publish apps in PlayStore, although this could easily break due to changes on google side.)

**Comment by lucasfernog** [comment]
#2588 #2583 #2589

**Comment by tweidinger** [comment]
it's not perfect and super overview'ish but I see this as initially completed.
