### ISSUE TITLE
[request] Embedding Additional Files page

### ISSUE THREAD

**Issue by joshtenorio** [tauri-apps/tauri-docs#2197]
### Question you want answered

How can I embed additional files?

### Where did you look for an answer?

I looked in `Guides > Develop`. There's some pertinent information in the [References > Configuration page](https://v2.tauri.app/reference/config#bundleconfig) to get started, but I think a page in the Guides section would be warranted especially when it comes to demonstrating how to access embedded files in Rust/JavaScript.

### Additional context

The Embedding Additional Files [page](https://tauri.app/v1/guides/building/resources) from the v1 docs exists, but hasn't been migrated to v2 yet.

In the [Upgrade from Tauri 1.0](https://v2.tauri.app/start/migrate/from-tauri-1) page there's a section for migrating embedded external binaries, so a section there for resources/files might be needed as well. The information to be updated here would include what pertinent JavaScript/Rust APIs have changed since 1.0 and steps/links to address these changes.

### Are you willing to work on this yourself?

- [X] I want to work on this myself

**Comment by simonhyll** [comment]
Awesome  that you're willing to work on it 🥳 If you need any help getting started don't hesitate to reach out in the `#docs` channel on Discord.

Seeing as we have a https://v2.tauri.app/develop/sidecar/ page, making one for additional assets next to it might be appropriate, like we have in v1
