### ISSUE TITLE
[Bug] Link to Migrate from Tauri 1 page is broken

### ISSUE THREAD

**Issue by kareemmahlees** [tauri-apps/tauri-docs#2211]
### Question you want answered

How to migrate from v1 to v2

### Where did you look for an answer?

.

### Page URL

https://v2.tauri.app/start/migrate/

### Additional context

The link that redirects to _Migrate from Tauri 1_ page is broken in the above mentioned page.

### Are you willing to work on this yourself?

- [X] I want to work on this myself

**Comment by vasfvitor** [comment]
hi, thanks for reporting this, what do you mean by 'broken'?
![firefox_ZBjaTyrngd](https://github.com/tauri-apps/tauri-docs/assets/61759797/d5bbf44d-b373-46ae-b8c3-3d6bd2ea7ac9)

**Comment by kareemmahlees** [comment]
@vasfvitor I get this blackout:
![image](https://github.com/tauri-apps/tauri-docs/assets/89863279/f44b0a13-e2b1-4b2b-a096-bb656ab9e539)

I am using Arc Browser, so I tried on Edge it worked the first time but the second time and onward it threw the same blackout, Same for Chrome 😕

**Comment by vasfvitor** [comment]
oh I got it to error on chrome in a guest profile, but not on firefox. It's related to the missing / at the end

**Comment by vasfvitor** [comment]
https://github.com/tauri-apps/tauri-docs/pull/2186

**Comment by kareemmahlees** [comment]
I can create a PR to fix this!
