### ISSUE TITLE
[request] Add libxdo-dev to Linux prerequisites

### ISSUE THREAD

**Issue by charles-r-earp** [tauri-apps/tauri-docs#2230]
### Question you want answered

Linux Prerequisites

### Where did you look for an answer?

I looked at https://beta.tauri.app/start/prerequisites/ and installed the required packages for Debian with:
```
sudo apt update
sudo apt install libwebkit2gtk-4.1-dev \
  build-essential \
  curl \
  wget \
  file \
  libssl-dev \
  libayatana-appindicator3-dev \
  librsvg2-dev
```
But I got `/usr/bin/ld: cannot find -lxdo: No such file or directory` when building. 

### Page URL

https://v2.tauri.app/start/prerequisites/

### Additional context

Installing libxdo-dev was suggested in this comment https://github.com/tauri-apps/tauri/issues/9005#issuecomment-2046268961 and resolved the issue for me. So I propose adding this to the documentation here https://github.com/tauri-apps/tauri-docs/blob/v2/src/content/docs/start/prerequisites.mdx.

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by simonhyll** [comment]
Added :)
