### ISSUE TITLE
Incorrect GitHub links get generated for the releases in v2 docs

### ISSUE THREAD

**Issue by TomDiekmann** [tauri-apps/tauri-docs#2240]
The link behind "View on GitHub" on the v2 release pages, which gets generated by build.ts of the release-generator package, is incorrect. It links to https://github.com/tauri-apps/tauri/release/... and not to the correct https://github.com/tauri-apps/tauri/releases/...

Example: https://v2.tauri.app/release/tauri-bundler/v2.0.1-beta.16/

**Comment by simonhyll** [comment]
Thanks for reporting the issue, fixed now :)
