### ISSUE TITLE
[request] Broken links

### ISSUE THREAD

**Issue by simonhyll** [tauri-apps/tauri-docs#2242]
### Question you want answered

Where did the user find broken links?

### Where did you look for an answer?

The page they linked to.

### Page URL

https://v2.tauri.app/reference/javascript/fs/#security

### Additional context

These links are broken, most likely broken upstream in the `tauri` repository.
<img width="704" alt="image" src="https://github.com/tauri-apps/tauri-docs/assets/79983560/bcb9fdfe-34bb-413e-b1c5-889efc440887">

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by GuoJikun** [comment]
https://beta.tauri.app/reference/javascript/api/namespacepath/#appcachedir

**Comment by derekblank** [comment]
Just noting that these URL linkcodes appear to come from the [plugins-workspace](https://github.com/tauri-apps/plugins-workspace) repo, specifically [guest-js/index.ts#L32-L56](https://github.com/tauri-apps/plugins-workspace/blob/ce9a97c45ce9a5551840c962018a59aebd5618eb/plugins/fs/guest-js/index.ts#L32-L56).

Not sure yet what the URLs should actually be, or why they're being transformed like they are.
