### ISSUE TITLE
[issue] Mermaid - Syntax error in graph

### ISSUE THREAD

**Issue by Binlogo** [tauri-apps/tauri-docs#2259]
https://tauri.app/v1/references/architecture/inter-process-communication/#commands

![image](https://github.com/tauri-apps/tauri-docs/assets/7845507/d1a0023f-852a-40c0-b2b7-93ae34cc7d5d)

**Comment by simonhyll** [comment]
That's weird, the page works just fine for me. Maybe you have an extension enabled that prevents the mermaid.js script from being ran? Or JS disabled for the site?

**Comment by Binlogo** [comment]
> That's weird, the page works just fine for me. Maybe you have an extension enabled that prevents the mermaid.js script from being ran? Or JS disabled for the site?

That's true, I try incognito mode it works fine. Since the "Figure 1-2: An event sent from the Core to the Frontend." works well, I didn't think of it. I got an extension changed the origin content. Thanks for your reply.
