### ISSUE TITLE
Better contributor guide & tools

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#23]
The https://github.com/tauri-apps/tauri/issues/564 issue has put a finger on something else that should be improved: having a a nice contributor guide in order to help people getting started quickly and easily so they can contribute to Tauri codebase.

**Comment by lorenzolewis** [comment]
Closing this as I feel it's addressed now with https://github.com/tauri-apps/tauri-docs/blob/dev/.github/CONTRIBUTING.md
