### ISSUE TITLE
[docs] External Binaries Path

### ISSUE THREAD

**Issue by SOVLOOKUP** [tauri-apps/tauri-docs#234]
Docs of Embedding External Binaries outdated in https://tauri.studio/en/docs/guides/bundler/sidecar:
![image](https://user-images.githubusercontent.com/53158137/121172285-1b0fe280-c88a-11eb-998d-84ca0621fee5.png)

Docs of command api 404 :
https://tauri.studio/en/docs/api/rust/tauri_api/command/fn.spawn_relative_command#function-tauri_apicommandspawn_relative_command

It seems that command api has changed in the latest version. Any new docs about how to get the path of the binary embedded ? I need to execute the binary in my tauri app.

**Comment by Laegel** [comment]
Hey @SOVLOOKUP , thanks for noticing this!
This is an old link, indeed, and it seems it's still appearing in the search results when it should not.

**Comment by SOVLOOKUP** [comment]
> Hey @SOVLOOKUP , thanks for noticing this!
> This is an old link, indeed, and it seems it's still appearing in the search results when it should not.

thanks for reply~ Could you give me some instructions about how to execute the embedded binary at the runtime? I cannot find enough docs to guide me...

**Comment by JonasKruckenberg** [comment]
https://tauri.studio/en/docs/api/rust/tauri/api/process/struct.Command#pub-fn-new_sidecars-intostringprogram-s---resultself worked for me, note though that the path is relative to the compiled binary (so it's relative to /target/debug) not to your source files (This caused me some confusion)

**Comment by SOVLOOKUP** [comment]
I found a demo of this.

https://github.com/Akryum/guijs/blob/40051bf07a2b9dc8dd0be19d15de93a84bed726c/packages/%40guijs/tauri-app/src-tauri/src/main.rs#L186

**Comment by lucasfernog** [comment]
The updated docs was merged on the main repo yesterday and will be available on the next release.
