### ISSUE TITLE
[bug] links are broken from fs plugin page

### ISSUE THREAD

**Issue by dakom** [tauri-apps/tauri-docs#2341]
### Question you want answered

how to use fs plugin

### Where did you look for an answer?

I tried searching via the docs, landed on a parent page just fine, but then links from there are broken

### Page URL

https://v2.tauri.app/reference/javascript/fs/

### Additional context

Many of the links from this page are 404, e.g. all the links from the `$FOO` style identifiers that I tried

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by tweidinger** [comment]
Seems to be fixed by #2416
