### ISSUE TITLE
[v1] Migrate documentation update workflows from v1 to v2 branch

### ISSUE THREAD

**Issue by simonhyll** [tauri-apps/tauri-docs#2363]
Currently the workflows that updates the v1 documentation hasn't been migrated from the v1 to the v2 branch. We'll need to get that fixed so that updates made to the core libraries are reflected in the generated documentaiton.

**Comment by FabianLars** [comment]
I'd prefer to keep the v1 workflows in the v1 branch (as much as possible at least) so i fixed the trigger on the tauri ci side instead. I also triggered the workflow manually once.

For the v2 branch i assume renovate updating the git submodules is enough for v2, right? In this case imho this issue can be closed.

**Comment by simonhyll** [comment]
Sounds good to me 👍🏻
