### ISSUE TITLE
[docs] npm vs Yarn confusion and onboarding

### ISSUE THREAD

**Issue by TheJaredWilcurt** [tauri-apps/tauri-docs#24]
https://github.com/tauri-apps/tauri/wiki/04.-MS-Windows-Setup

The documentation makes it sound like tauri cannot function without Yarn, and that npm should not be used, which is completely backwards to everything in the Node.js ecosystem. Node ships with npm and only a small minority of projects use Yarn (let alone require it).

Further, for onboarding new users the ideal scenario would be:

1. Install Node.js and npm
2. `npm install -g @tauri/cli`
3. `tauri my-app-name`
4. `cd my-app-name && npm start`

But my expectations are that it at least be:

1. Install Node.js and npm
2. `npm init -y`
3. `npm install --save-dev tauri`
4. Edit your `package.json` to point the `main` to `index.html`
5. Create an `index.html`
6. `npx tauri .`

**Comment by TheJaredWilcurt** [comment]
The `npx` part is just a placeholder until [`npm set-script start "tauri ."`](https://github.com/npm/rfcs/blob/latest/accepted/0016-set-script-command.md) is implemented. it's just easier than making a step saying:

> Edit the `package.json` and find the `"scripts"` section, then create or modify a `"start"` script with the value `"tauri ."`.

**Comment by TheJaredWilcurt** [comment]
This issue was closed, however the documentation is still confusing and makes it sound like yarn and scoop are a prerequisite for Tauri to work (HUGE turn off from an onboarding perspective).

After installing Node, you'll already have npm. You don't need to install scoop or yarn. these are just extra steps added to the barrier of entry that slow down and confuse new users and are additional points of failure where something may not work properly.

Onboarding should be as streamlined as possible, removing any steps that can be skipped.

This is what you are competing with:

## NW.js

**Prerequisites:**

1. Install [Node.js](https://nodejs.org) and npm (version doesn't matter)
   * `npm` comes with Node on Windows and OSX

**Steps to making your first desktop app:**

1.  Make an HTML5 file (it can even just be an empty file) called `index.html`
1. Create a `package.json` file like so:
   ```json
   {
     "name": "my-first-desktop-app",
     "main": "index.html",
     "scripts": { "start": "nw" }
   }
   ```
1. run `npm install --save-dev nw@sdk && npm start`

There we go. 1 global install, 2 files, 3 lines of code, 1 command. No OS specific instructions.

## Electron (Real)

**Prerequisites:**

1. Install [Node.js](https://nodejs.org) and npm (version doesn't matter)
   * `npm` comes with Node on Windows and OSX

**Steps to making your first desktop app:**

1.  Make an HTML5 file (it can even just be an empty file) called `index.html`
1. Create a `package.json` file like so:
   ```json
   {
     "name": "your-app",
     "version": "0.1.0",
     "main": "main.js",
     "scripts": { "start": "electron ." }
   }
   ```
1. Create a `main.js` file like so:
   ```js
   const { app, BrowserWindow } = require('electron');

   function createWindow () {
     let win = new BrowserWindow({
       width: 800,
       height: 600,
       webPreferences: {
         nodeIntegration: true
       }
     });
     win.loadFile('index.html');
   }

   app.whenReady().then(createWindow);

   app.on('window-all-closed', () => {
     if (process.platform !== 'darwin') {
       app.quit();
     }
   });

   app.on('activate', () => {
     if (BrowserWindow.getAllWindows().length === 0) {
       createWindow();
     }
   });
   ```
1. run `npm install --save-dev electron && npm start`

There we go. 1 global install, 3 files, 21 lines of code, 1 command. No OS specific instructions.

## Electron (cheat)

Electron is actually not that great, so they cheat by telling people to use this instead:

**Prerequisites:**

1. Install [git](https://git-scm.com) (version doesn't matter)
1. Install [Node.js](https://nodejs.org) and npm (version doesn't matter)
   * `npm` comes with Node on Windows and OSX

**Steps to making your first desktop app:**
1. Run `git clone https://github.com/electron/electron-quick-start`
1. Run `cd electron-quick-start`
1. Run `npm install && npm start`

There we go. 2 global installs, 0 files, 0 lines of code, 3 commands. No OS specific instructions.

* * *

That's how you should be thinking about this. How do you reduce the number of global installs, files, lines of code, commands, and OS specific instructions to get from nothing, to having a window opened with a blank screen/hello world.

**Comment by Laegel** [comment]
You're right, sorry, I didn't notice you were talking about OS-specific installations. Alright, I'll try to rework those parts, too. Thanks for your insight!

**Comment by nothingismagick** [comment]
Probably shouldn't have closed it on you sorry. I'd like to see your rewrite though @TheJaredWilcurt . How should we be saying this?

**Comment by TheJaredWilcurt** [comment]
This is basically what you already have but simplified where possible.

* Each step is numbered, since almost every step requires going to a new tab or running a command in another window, this makes keeping track of what step you were on easier.
* Added in a note for WSL users so they know that their instructions are on another page. Not entirely sure if they should be on that page or not, but I haven't read the Linux page yet, so I'll assume that it is a good choice for now.
* Build Tools
   * Used the correct name `Build Tools for Visual Studio 2019` to match what the website you are linking to calls it so the user is not confused and knows to download the correct thing.
   * Added a reason for *why* they need that. (not sure if accurate)
   * Would be better if you could explain *how* to check if you already have the 2017 version.
   * Would also be nice if this could be automated via an `npm install` similar to [Windows-Build-Tools](https://github.com/nodejs/node-gyp#on-windows). So you don't need to go to a website and do it manually.
* Removed stuff around nvm-windows. This isn't a bad recommendation, it's just out of scope for your project. Especially since, to install nvm on Windows without weird PATH/env conflicts you need to uninstall any existing Node versions first. There's just many steps and caveats like "If you aren't on Windows 10 you may need to install `nodist` instead" which has a different API. And `nvm-windows` does not support a `nvm use latest`, though I created [an issue](https://github.com/coreybutler/nvm-windows/issues/543) requesting this feature.
* Removed Yarn and Scoop stuff. Not needed. Just use npm. This means that other pages that come after this would need to be updated similarly.
* Simplified Rust instructions
* Is there any way loopback could be automated? Maybe as part of the `tauri-bundler` install. This seems like a pretty silly step for each user to have to do by hand just for a Hello World.
* I moved the DevTools to the optional section, but when competing against other modern XPDA tooling, not having dev tools built in is a big CON on the Pros/Cons list for Tauri. I've created an issue on the [Edge Repo](https://github.com/MicrosoftDocs/edge-developer/issues/723) to get a non MS Store link, as that is another barrier of entry. However, not knowing what their response will be, or why the Edge DevTools specifically are needed, I'm curious if there is anyway you could get headless chrome remote devTools to work? Especially with Edge being Chromium-based now. There are many Node modules that automate downloading/setting up these dev tools. It would be much more preferable for devTools to come pre-packaged with Tauri. Even if that means your dev environment is in Chrome and the production runs on Edge. Since they're both Chromium now, the differences between the two should be minor. Maybe have that as the default with an option you can set to run it in dev against Edge with the extra documentation around setting up the Edge DevTools.
* There's A LOT of stuff required right now for a simple hello world. Any efforts you can make on slimming down these prereqs will be effort well spent.

* * *

# Setup for Windows

**Note:** For those using the **Windows Subsystem for Linux (WSL)** please refer to our [Linux specific instructions](https://tauri.studio/docs/getting-started/setup-linux#for-windows-subsystem-for-linux-wsl-users) instead.

## Prerequisites

**Note:** "Run" means to type a command into a Command Prompt or Powershell running with administrative privileges. 

1. Install [Build Tools for Visual Studio 2019](https://aka.ms/buildtools)
   * This is needed for when we build the native version of your app.
   * If you have the 2017 version installed, you may need to remove that first to avoid issues later when doing `tauri build`.
1. Install [Node.js](https://nodejs.org) and npm 
   * npm comes with Node on Windows and OSX
1. Install Rust
   * [Windows 64-Bit Rust installer](https://win.rustup.rs/x86_64)
   * [Windows 32-Bit Rust installer](https://win.rustup.rs/i686)
1. Update Rust by running `rustup update stable`
1. Enable Loopback. Microsoft disables the loopback interface by default. It is needed to use the dev-server.
   * Run
   ```
   CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
   ```
1. Close your command prompt/powershell and relaunch it
1. Run `cargo install tauri-bundler --force`

**Optional:**

1. If you want to debug the front-end you will have to download [Microsoft Edge Devtools](https://www.microsoft.com/store/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj) from the Microsoft store. This will allow you to attach to a running instance of your Tauri project! If you need help take a look at the [devtools-guide](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide).

* * *

This gets you down to 3 global installs and 3 commands. But doesn't actually get you all the way to a Hello world. there will be files and lines of code, and these are all OS Specific instructions. Though the Node and Rust stuff could probably be moved out to a non-OS specific section.

**Comment by Laegel** [comment]
Hey @TheJaredWilcurt,

Thanks for your awesome comment.
I tried to mix your feedback to what we already had (see https://deploy-preview-57--tauri.netlify.app/docs/getting-started/setup-linux/, only "Setup Linux" is ready for now; the pages need refactoring). 
Note that as Tauri is more complex to setup than Electron or NW.js, it's normal that we get extra instructions than they do.

Through these guides, we genuinely tried to provide an educational (and with security in mind!) way to setup Tauri: we're assuming people already know how to setup things but not necessarily Node.js and/or Rust. It's a complete "stay on track" guide. 
The first time I've installed Tauri requirements, I only had Node.js/nvm installed and knew nothing about Rust. Reading, copy/pasting allowed me to have it running _without a single issue_. That was pretty encouraging.
By following these guides, people don't need to browse the web for learning how to setup these requirements. 

I know, for people used to play with Node.js, this guide can look a bit redundant or impressive. That's why I've added some icons/colors so people know immediately what can be skipped or not.

What do you think about these improvements?

**Comment by TheJaredWilcurt** [comment]
https://github.com/MicrosoftDocs/edge-developer/issues/723#issuecomment-638642445
