### ISSUE TITLE
Contributing guides, let's sort those out, and get consensus

### ISSUE THREAD

**Issue by thadguidry** [tauri-apps/tauri-docs#241]
Currently it seems the canonical [CONTRIBUTING.md](https://github.com/tauri-apps/tauri/blob/dev/.github/CONTRIBUTING.md) file within Tauri's main repo has most of all the details I'd expect as a new developer coming into this wonderful community.  Irregardless of contributing Code, or Documentation, or hacking on improving the CI/CD.  It basically has the "rules" or the "do's and do not's" of how to contribute to the project and then "the good stuff" or "how to contribute if I'm brand new".  Let's review with GitHub's own verbage of what "contribution guidelines" are however...

> For the repository owner, contribution guidelines are a way to communicate how people should contribute.
>
> For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.
>
> For both owners and contributors, contribution guidelines save time and hassle caused by improperly created pull requests or issues that have to be rejected and re-submitted.
>

Notice the phrase "how people should contribute" in the quote.  That probably throws a lot of repo admins off.  It's not really the "how".  Notice the 2 additional lines.  Instead, it's actually the **WHAT RULES TO FOLLOW WHEN CONTRIBUTING**.  The HOW can actually be in another file something like a CONTRIBUTING QUICK START guide.

Notice what GitHub suggests for content in a `CONTRIBUTING.md` file
>
> In the new file, add contribution guidelines. These could include:
>
>   Steps for creating good issues or pull requests.
>   Links to external documentation, mailing lists, or a code of conduct.
>   Community and behavioral expectations.

Let's explain... `CONTRIBUTING.md` currently has many details (which are important and great!) but sometimes might be overkill if we want folks to actually contribute ... I.E. it's very wordy (for good reason! since we need a document to hold the "rules" to follow when contributing to the project and it's documentation.)

Hence, it appears that the start of a CONTRIBUTING QUICK START guide is in progress over in the docs repo here:
https://github.com/tauri-apps/tauri-docs/blob/dev/docs/en/usage/contributor-guide.md

That's Great!
So... in summary...

We have the `CONTRIBUTING.md` which should only be the **WHAT RULES TO FOLLOW WHEN CONTRIBUTING**.
We then have `CONTRIBUTING_QUICK_START.md` (renamed) where this quick start guide would start off with a sentence and link to the `CONTRIBUTING.md` guide for rules.  `CONTRIBUTING_QUICK_START.md` could then describe the HOW to quickly get folks contributing (git pull, file structure areas, etc.)

Thoughts ?
Concerns on folks "breaking the rules when creating PR's" ?

Concerns could be mitigated of course by having links prominently on the main repo's `README.md` file and we already have a good PR template it seems.  But it might need to include a few nice things moved out of the `CONTRIBUTING.md` file and into it.  As well as the PR template having a link to the new `CONTRIBUTING_QUICK_START.md` ?

**Comment by thadguidry** [comment]
Issue #23 basically describes a bit of the QUICK START idea and I guess why it has come into fruition.  But we still need this issue to sort things out and come to some consensus on the previous comment.

**Comment by lorenzolewis** [comment]
Closing this as we've since introduced a contributing file and are planning on getting rid of the guide on the hosted site (will only be on GitHub)
