### ISSUE TITLE
Mistake in guide about clipboard plugin

### ISSUE THREAD

**Issue by StepanZagray** [tauri-apps/tauri-docs#2412]
### Discussed in https://github.com/tauri-apps/tauri/discussions/10290

<div type='discussions-op-text'>

<sup>Originally posted by **pan-grayza** July 15, 2024</sup>
Here are [docs](https://v2.tauri.app/plugin/clipboard/).
Code from guide:
```Rust
use tauri_plugin_clipboard_manager::ClipboardExt;

// Write content to clipboard
let clipboard_content = tauri_plugin_clipboard_manager::ClipKind::PlainText {
    label: Some("Label".to_string()),
    text: "Tauri is awesome!".to_string(),
};
app.clipboard().write(clipboard_content).unwrap();

// Read content from clipboard
let content = app.clipboard().read();
println!("{:?}", content.unwrap());
// Prints "Tauri is awesome!" to the terminal
```
it needs to be `write_text()` and `read_text()` instead of `write()` and `read()` [plugin code](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/clipboard-manager/src/commands.rs)

The question is, where are `app` and `ClipKind` appears from? 
`ClipKind` does not exists in that path
And why we are importing `use tauri_plugin_clipboard_manager::ClipboardExt;` when we are not it using anywhere?

</div>

**Comment by FabianLars** [comment]
> it needs to be write_text() and read_text() instead of write() and read() [plugin code](https://github.com/tauri-apps/plugins-workspace/blob/v2/plugins/clipboard-manager/src/commands.rs)

Good catch, we didn't update that when we updated the apis a few months ago.

> The question is, where are app appears from?

Copy paste from the linked discussion: "`app` is supposed to be an AppHandle instance which you have access to in the `setup` hook or in commands via https://v2.tauri.app/develop/calling-rust/#accessing-an-apphandle-in-commands"

We need to make this clearer somehow, so thanks for the feedback.

> The question is, where are ClipKind appears from?

ClipKind is also from before the api update and does not exist anymore.

>  And why we are importing use tauri_plugin_clipboard_manager::ClipboardExt; when we are not it using anywhere?

This makes the `app.clipboard()` call possible.
