### ISSUE TITLE
[request] increase depth for TOC in the right side of references pages

### ISSUE THREAD

**Issue by arkhaiel** [tauri-apps/tauri-docs#2444]
### Question you want answered

Can you increase depth of titles in TOC for references pages ?

### Where did you look for an answer?

I just spent like 15' exploring the source of this repo, the Astro docs, and couldn't find any information related to TOC depth.

### Page URL

[v2 Store Reference](https://v2.tauri.app/reference/javascript/store/#store)

### Additional context

Let's take this page : https://v2.tauri.app/reference/javascript/store/#store

The class store has many methods, the methods are not shown in the TOC on the right side of the screen, and it's difficult to get quickly what we would need.

I'm definitely not used to Astro and I can't find where you generate the TOC so I'm afraid I won't be able to help, but I'm new to Tauri and I certainely will spent A LOT of time reading the API references, and this small tweak would surely lead to better comfort.

Thanks a lot !

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by simonhyll** [comment]
We can certainly do that, not sure which depth we'd wanna do though 🤔
For reference it's a simple frontmatter updater, e.g. `tableOfContents.maxHeadingLevel: 6`
