### ISSUE TITLE
Add caution admonition to ensure users check for 'tauri:' in CSP output

### ISSUE THREAD

**Issue by thadguidry** [tauri-apps/tauri-docs#249]
Based on [comment](https://github.com/tauri-apps/tauri/issues/2089#issuecomment-869054772) from @nothingismagick 
, we probably should do the follow tasks:
- [ ] use a [docusaurus `:::caution` admonition](https://docusaurus.io/docs/next/markdown-features/admonitions) to ensure that folks are aware to check for `tauri:` in the CSP output from `tauri info`.
The best place for this admonition would probably be at L116 in 
https://github.com/tauri-apps/tauri-docs/blob/dev/docs/en/usage/development/integration.md#L116
just after the `tauri info` output https://github.com/tauri-apps/tauri-docs/blob/dev/docs/en/usage/development/integration.md#3-check-tauri-info-to-make-sure-everything-is-set-up-properly

- [ ] And within the admonition, add link to Api Configuration docs new section entitled `CSP` where we can explain a few more things in more detail by adding a paragraph or admonition into that new section.  This new `CSP` section can be added into the tauri config perhaps above the `example`?  See PR #249 DRAFT that needs help for this.

**Comment by lucasfernog** [comment]
Closing since we're planning a dedicated security & csp documentation this weekend.
