### ISSUE TITLE
[bug] Translation problem of the "plugin/notification" document.

### ISSUE THREAD

**Issue by lersmare** [tauri-apps/tauri-docs#2497]
### Question you want answered

There is a problem with the translation of the "plugin/notification" document.

### Where did you look for an answer?

Here is the translation of document in chinese.
https://github.com/tauri-apps/tauri-docs/blob/v2/src/content/docs/zh-cn/plugin/notification.mdx
![image](https://github.com/user-attachments/assets/b4e770df-cb4f-42f9-b064-3bec27cad932)
And here is the original document.
https://github.com/tauri-apps/tauri-docs/blob/v2/src/content/docs/plugin/notification.mdx
![image](https://github.com/user-attachments/assets/14e7e4a5-3dea-4d3e-ac98-ef9363935dcd)

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by vasfvitor** [comment]
thanks for reporting, I'll look around for similar issues and fix this one
