### ISSUE TITLE
[request] Windows page for code sigining in Distribute section

### ISSUE THREAD

**Issue by anatawa12** [tauri-apps/tauri-docs#2506]
### Question you want answered

How can I sign windows executable and instealler

### Where did you look for an answer?

I checked https://v2.tauri.app/distribute/ and there is no (stub) page for windows signing.

in v1, there was: https://tauri.app/v1/guides/distribution/sign-windows

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by anatawa12** [comment]
I think mentioning relationship with configuration keys and parameter of signtool, and mentioning `signCommand` is enough so page size will be small but I think such document should be listed on documentation page.

**Comment by RemcoDewlde** [comment]
I believe this is what you are looking for: https://v2.tauri.app/distribute/sign/windows/ and/or https://v2.tauri.app/distribute/windows-installer/

**Comment by FabianLars** [comment]
whoops, we forgot to close this issue after adding the guides. Thanks!
