### ISSUE TITLE
tauri.conf.json, package.json, Cargo.toml

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-docs#252]
There are many places to configure things, and we need to do not only a better job documenting all the possibilities, but also explain how they interact and impact a project.

I am thinking we need a whole section about this, with a general overview and then individual pages for each of these.

**Comment by Laegel** [comment]
I guess being more explicit for package.json and Cargo.toml is respectively for Rust devs and JS devs who may be lost, right?

**Comment by nothingismagick** [comment]
Yeah, I think everyone should be able to inform themselves of what everything means to tauri, regardless of where they come from.

**Comment by lorenzolewis** [comment]
@JonasKruckenberg we have this bit repeated in all the guides. I think it would make sense to move this to the "Architecture" section (with a link in the docs) and take that as an opportunity to address this as well. Thoughts?

<img width="989" alt="Screenshot 2022-07-15 at 20 48 16" src="https://user-images.githubusercontent.com/15347255/179300310-c332b9dc-18d6-43d9-8302-69dabef44b34.png">

**Comment by JonasKruckenberg** [comment]
Hmmm. I agree it would make sense to have this in an architecture guide, but Imo the getting started pages should be as self contained as possible. We don't wanna risk loosing/having people bounce bc they got confused by so many links to all over the place 🤔

**Comment by lorenzolewis** [comment]
Maybe we leave it as-is in the guides and just have a link with "go here to learn more about these..."

**Comment by JonasKruckenberg** [comment]
Yeah that sounds like a great idea 👍
