### ISSUE TITLE
[request] There is a problem with the shell plugin documentation

### ISSUE THREAD

**Issue by GuoJikun** [tauri-apps/tauri-docs#2539]
### Question you want answered

Shell plugin configure

### Where did you look for an answer?

Could not find the correct configuration.

### Page URL

https://beta.tauri.app/plugin/shell/

### Additional context

![image](https://github.com/user-attachments/assets/42361751-bb32-46bb-953d-f667f063786a)
![image](https://github.com/user-attachments/assets/3bad17ed-c6d5-46d4-8aab-b743ccc95af4)
![image](https://github.com/user-attachments/assets/3d04be5a-0986-4f13-a13e-5bfaa7d24810)

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by FabianLars** [comment]
Did you mean this page? https://v2.tauri.app/reference/javascript/shell/ 
That's fixed in https://github.com/tauri-apps/tauri-docs/pull/2541
