### ISSUE TITLE
Error in CLI json

### ISSUE THREAD

**Issue by ppom0** [tauri-apps/tauri-docs#257]
In the en and [fr](https://github.com/tauri-apps/tauri-docs/blob/f488410eb02991522f38e45e8b1c9d4fd7c9f1e3/docs/fr/usage/guides/cli.md) markdowns, there is an error in heading "Flag arguments":
```
{
  "args": [
    "name": "verbose",
    "short": "v",
    "multipleOccurrences": true
  ]
}
```
should be: 
```
{
  "args": [{
    "name": "verbose",
    "short": "v",
    "multipleOccurrences": true
  }]
}
```

**Comment by lorenzolewis** [comment]
Will be closed by #604
