### ISSUE TITLE
[docs] Bad URLs on the about page

### ISSUE THREAD

**Issue by jonathanyeong** [tauri-apps/tauri-docs#2580]
All the links on the [about page](https://v2.tauri.app/about/) do not load in chrome. It seems like this issue is isolated to chromium browsers. It works in safari and firefox. 

Tested on Chrome 128.0.6613.85

![CleanShot 2024-08-23 at 18 30 12](https://github.com/user-attachments/assets/cf99c34e-668b-4e6d-aa82-29c0e27c0492)

I noticed this comment:

```
  // TODO: Fix trailing slashes throughout the docs
  // trailingSlash: 'always',
```

Should we be adding trailing slashes to all URLs? I'm happy to do it. But wondering if that's the direction tauri docs want to go.

**Comment by vasfvitor** [comment]
probably solved in #2802
