### ISSUE TITLE
make create-tauri-app visible / mention in docs as easy start

### ISSUE THREAD

**Issue by 6543** [tauri-apps/tauri-docs#259]
Make this command visible in docs and mention it as one of the easyest ways to o start with tauri

```sh
yarn global add create-tauri-app
create-tauri-app
```
or
```sh
npx create-tauri-app
```

**Comment by Laegel** [comment]
Hey, thanks for this issue. I've already started working on it, although there was no related issue.

**Comment by lorenzolewis** [comment]
Closing with our recent updates to the docs and the home page.
