### ISSUE TITLE
[docs][v1] path to executable seems misleading

### ISSUE THREAD

**Issue by hchiam** [tauri-apps/tauri-docs#2692]
i've been enjoying [learning about tauri](https://github.com/hchiam/learning-tauri) and i tried building to a desktop app, and to me the file path of the executable file seems a little misleading:
https://tauri.app/v1/guides/distribution/publishing/
says the file should be at:
`src-tauri/target/release/`[app name]

and when i ran `yarn tauri build`, there is technically a runnable file at that path, but oddly the file name didn't have a file extension, and i noticed that when the file runs, it also runs a terminal in the background (not the cleanest UX),

but i happened to [notice the file path in a youtube video (13:35)](https://youtu.be/_dJDjVG1wWs?si=Z6j7Ec_YFeDC3oIu&t=812) that made me realize that the executable .app file for mac that i was looking for is actually here:
`src-tauri/target/release/bundle/macos/`[app name.app]

as a beginner, this could be made clearer, but maybe the docs will change anyways for v2

**Comment by hchiam** [comment]
Maybe examples for the binary and installer can be added for clarity?

**Comment by FabianLars** [comment]
> and when i ran yarn tauri build, there is technically a runnable file at that path, but oddly the file name didn't have a file extension, and i noticed that when the file runs, it also runs a terminal in the background (not the cleanest UX),

Binaries don't have file extensions on macos and linux so the docs are technically correct. You just can't really use that binary so mentioning it doesn't make _that_ much sense. You really only need to know about the binary if you package your own installer (and on Windows where standalone binaries are actually a thing for gui apps)

`.app` is not a binary but a directory, it's just handled in a special way by macOS 🤷 Comparing it with the v2 docs (with your PR in mind) i think the proper doc update would be something like changing "installers" to "bundles and installers" (.app being an Application Bundle)


> but maybe the docs will change anyways for v2

Yes they will, binaries as of yet aren't mentioned anymore: https://v2.tauri.app/distribute/
