### ISSUE TITLE
[docs] Missing example for execute API

### ISSUE THREAD

**Issue by x7airworker** [tauri-apps/tauri-docs#27]
I am searching for documentation / example of the execute API.

**Comment by aafnnp** [comment]
it's necessary, I don’t know how to implement it.

**Comment by Laegel** [comment]
Hey @funnyPan, you can find a small example right here: https://tauri.studio/en/docs/api/js/#process
Is it enough?

**Comment by aafnnp** [comment]
> Hey @funnyPan, you can find a small example right here: https://tauri.studio/en/docs/api/js/#process
> Is it enough?

not enough.

`import { open, save } from 'tauri/api/dialog'
open(...); save(...);
// alternatively:
import * as dialog from 'tauri/api/dialog'
dialog.open(...); dialog.save(...)`

such this.i don't know how to use it with arguments.
