### ISSUE TITLE
Broken link on v2.tauri.app/blog

### ISSUE THREAD

**Issue by Remzi1993** [tauri-apps/tauri-docs#2720]
### Question you want answered

There is a broken link

### Where did you look for an answer?

There is a broken link and I don't know where to create a new issue about it.
It's on the https://v2.tauri.app/blog/ and it's about the link: [Tauri Board Elections 2024](https://v2.tauri.app/blog/tauri-board-elections-2024)

The link is: https://v2.tauri.app/blog/tauri-board-elections-2024
And should be: https://v2.tauri.app/blog/tauri-board-elections-2024/   (ending with a slash /)

### Page URL

https://v2.tauri.app/blog/

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by vasfvitor** [comment]
thanks for reporting, we've been having issues with missing trailing slashes at the docs

**Comment by vasfvitor** [comment]
as I'm seeing, potentially all blog posts have this issue. I can't reproduce them, but I know it happens. Did you had any issue with other blog post?

**Comment by Remzi1993** [comment]
> as I'm seeing, potentially all blog posts have this issue. I can't reproduce them, but I know it happens. Did you had any issue with other blog post?

I didn't seem to have any issues with other blog posts, but I didn't check all of them, so I don't know.

Maybe an idea? Why not make the links work with both / at the end and without it?

**Comment by vasfvitor** [comment]
> Maybe an idea? Why not make the links work with both / at the end and without it?

they should, at least for most users it works either way (for me it does), but, strangely, sometimes fails without '/'

**Comment by Remzi1993** [comment]
> > Maybe an idea? Why not make the links work with both / at the end and without it?
> 
> they should, at least for most users it works either way (for me it does), but, strangely, sometimes fails without '/'

Maybe it's browser specific, I use Google Chrome.

**Comment by tweidinger** [comment]
Can't reproduce on chrome. Get an automated rewrite of the link to use a trailing slash. Feel free to re-open if still an issue.
