### ISSUE TITLE
Getting started tutorial doesn't explain where HTML/CSS go

### ISSUE THREAD

**Issue by kornelski** [tauri-apps/tauri-docs#274]
The getting started tutorial at https://tauri.studio/en/docs/development/integration

mentions using Vue ("If you are using Vue CLI"), but doesn't explain what to do if I'm *not* using Vue.

I've followed the tutorial to the end. I've got the Rust side working, but the window is completely blank. If I inspect it, it's just an empty body. There's no HTML anywhere in my project, and I'm surprised that the project even builds without some kind of HTML bootstrap template.

The project structure shown at:

https://tauri.studio/en/docs/development/integration#2-initialize-tauri-in-your-app

doesn't show any HTML or JS files.

In the documentation there's a list of architectural patterns with various levels of complexity of the HTML/JS side, but none of them explain how to implement them, apart from just one config file, but the config alone isn't enough to get an application running.

So where does HTML/CSS go, if I'm not using Vue?

I've tried searching for projects using Tauri, but all I could find use big JS frameworks and have complex build systems, and I really want to avoid that. Primary reason why I'm interested in Tauri is that I'm looking for an alternative to JS and Node.js.

**Comment by JonasKruckenberg** [comment]
Will be tracked over at #441
