### ISSUE TITLE
[request] Does v2 documentation seem to be progressing slowly? 

### ISSUE THREAD

**Issue by RSS1102** [tauri-apps/tauri-docs#2756]
### Question you want answered

t was difficult for me to find a complete example of using menu on tauri2 through Google and GitHub source code searches

### Where did you look for an answer?

Does v2 documentation seem to be progressing slowly? It seems that the v2 document commit is close to stopping.
excluded [renovate[bot]](https://github.com/apps/renovate)‘s commit.
![image](https://github.com/user-attachments/assets/74150cb6-03d7-4f1b-b79d-83285e257d05)

For example, I searched for menu examples about v2 for a long time, but couldn't find specific code instructions or related examples... Only the interface description generated by cargo... This creates a big obstacle for users to replace v2.

### Page URL

https://v2.tauri.app/reference/javascript/api/namespacemenu/#_top

### Additional context

So are there any specific plans for v2 documentation?
After the rc phase, will the v2 api for tauri not change? (More of a fix or optimization?)

### Are you willing to work on this yourself?

- [ ] I want to work on this myself

**Comment by RSS1102** [comment]
https://v2.tauri.app/start/migrate/from-tauri-1/#migrate-to-menu

It looks like the upgrade guide for the v2 menu, but it still seems a bit inconsistent with the rc features, so I haven't run it successfully.

However, it seems that you can refer to this v2 document for enrichment

**Comment by RSS1102** [comment]
` app.set_menu(menu);`
Looks like this is missing.
=.=|||

**Comment by tweidinger** [comment]
Closing this as I can't see anything helpful for the docs issues.
