### ISSUE TITLE
[v2-bug] Non-existent document link

### ISSUE THREAD

**Issue by RSS1102** [tauri-apps/tauri-docs#2787]
### Question you want answered

Non-existent document link

### Where did you look for an answer?

https://tauri.app/develop/calling-frontend/#global-events
![image](https://github.com/user-attachments/assets/d757f6ee-cbad-4630-84ca-93d5402b25cd)

https://tauri.app/develop/calling-rust

### Are you willing to work on this yourself?

- [x] I want to work on this myself

**Comment by RSS1102** [comment]
These are also
![image](https://github.com/user-attachments/assets/54d035be-b2b8-486c-80c5-98f1b29badab)

**Comment by vasfvitor** [comment]
I think the issue in the first one is the missing trailing slash, it's been happening but not always, I can't reproduce it, it's rare but happens. The second url is indeed broken, you'd save to search Rust docs for Tauri to see where is it

**Comment by RSS1102** [comment]
> I think the issue in the first one is the missing trailing slash, it's been happening but not always, I can't reproduce it, it's rare but happens. The second url is indeed broken, you'd save to search Rust docs for Tauri to see where is it

Thank you, you're right.
It seems that some other links in v2 also have similar two issues
1. There is no tail diagonal line.
2. Rust docs pointing to v2 is incorrect.
