### ISSUE TITLE
[docs] clicking link in docs brings to 404

### ISSUE THREAD

**Issue by ArthurTimofey** [tauri-apps/tauri-docs#2812]
![image](https://github.com/user-attachments/assets/497efbf0-30d1-450f-bd2f-6dea443f991b)

https://tauri.app/concept/architecture/

Edit: actually its all 3 of the links:

`custom menus` - 404
`tray-type-interfaces` - 404
`updated` - 404

**Comment by vasfvitor** [comment]
thanks for reporting #2802 should fix them
