### ISSUE TITLE
Pacman/Arch dependencies

### ISSUE THREAD

**Issue by LukasDoesDev** [tauri-apps/tauri-docs#290]
Can the `--needed` flag be added to the Pacman/Arch dependencies command at [the Linux setup page](https://tauri.studio/en/docs/getting-started/setup-linux)?

**Comment by LukasDoesDev** [comment]
It will skip all dependencies which are up to date and installed.

**Comment by FabianLars** [comment]
https://github.com/tauri-apps/tauri/pull/2666
already done, but not published.

**Comment by LukasDoesDev** [comment]
Great :+1:
