### ISSUE TITLE
Broken numbering on Integration page

### ISSUE THREAD

**Issue by kimlimjustin** [tauri-apps/tauri-docs#291]
Hello, I was going to test Tauri for [my project](https://github.com/kimlimjustin/xplorer) and when looking at the documentation, I realized that the numbering on the Integration page is off.

![image](https://user-images.githubusercontent.com/61906684/135835959-2893bb71-b8de-4164-adf5-dab2846c4f19.png)
![image](https://user-images.githubusercontent.com/61906684/135835997-28f54193-37b1-4b3f-a817-c0565dee1521.png)

I know that this is a small mistake, but it is always better to have fewer mistakes, isn't it? Hence, I open this issue

Also, I actually don't know where to open this issue as the docusaurus website is on Tauri not this, but I saw that this repo is for the docs, so I decided to open it here.

I could fix this issue by PR if you'd like to :)

Thanks and Regards

**Comment by lucasfernog** [comment]
This is fixed on the next branch on this repo. Thanks for opening this issue though :)

**Comment by FabianLars** [comment]
That screenshot is from the next branch tho: https://github.com/tauri-apps/tauri/blob/next/docs/usage/development/integration.md
There are indeed two lines starting with `### 1.`, but it also kinda makes sense as those steps are like "either this or that, not both".

**Comment by kimlimjustin** [comment]
> That screenshot is from the next branch tho: https://github.com/tauri-apps/tauri/blob/next/docs/usage/development/integration.md There are indeed two lines starting with `### 1.`, but it also kinda makes sense as those steps are like "either this or that, not both".

IDK from where's the docs site is but that's the problem haha, especially the latest sentence.
