### ISSUE TITLE
[request] toggle all code previews between Rust and Javascript

### ISSUE THREAD

**Issue by 0xbrayo** [tauri-apps/tauri-docs#2941]
### Question you want answered

More of a feature request

### Where did you look for an answer?

In the website?

### Additional context

It's annoying and tiresome keeping on switching each subsequent codeblock to rust from the default value of javascript. If I switch a single codeblock in the page it should switch all of them to rust. Like how firebase docs does it. Willing to  work on this if it will get merged sooner.

### Are you willing to work on this yourself?

- [X] I want to work on this myself

**Comment by FabianLars** [comment]
Yes good call. I was honestly just too lazy to do that when I added this to the package manager tabs

**Comment by vasfvitor** [comment]
starlight supports it now https://starlight.astro.build/components/tabs/#sync-tabs

**Comment by 0xbrayo** [comment]
Will check into , should have the PR ready by tomorrow
