### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by ghost** [tauri-apps/tauri-docs#295]
When searching for something, I get cross origin related errors, on Firefox v94:

![grafik](https://user-images.githubusercontent.com/23178554/142318274-72873595-c166-4dc8-869b-f9763c1fddaa.png)
(The German text is basically saying that the request was blocked due to CORS)

![grafik](https://user-images.githubusercontent.com/23178554/142318929-88ba2195-0019-4cfc-8018-e9cadba0fabf.png)

Is there any more info that I can give?

**Comment by FabianLars** [comment]
Yeah we know about that and our discord search bot is broken too. We're working on it. Thanks for reporting!
