### ISSUE TITLE
[suggestion] Make the "https://v2.tauri.app" domain redirect to "https://tauri.app" or vice versa

### ISSUE THREAD

**Issue by Hassunaama** [tauri-apps/tauri-docs#2999]
Since Tauri v2 was released, both domains (v2.tauri.app & tauri.app) have showed the same page. So I thought maybe one of the pages could redirect to the other one.

Any thoughts?

**Comment by FabianLars** [comment]
thanks for the suggestion.

idk about the rest of the team but i'm against it. v1.tauri.app, v2.tauri.app, etc should always point to the respective docs version and never redirect to tauri.app that wouldn't make sense imo.

i wouldn't fight a tauri.app -> v2.tauri.app redirect but i would still prefer not to have it. i don't like changing user facing redirects (idk how to call it) on each release and i assume many people prefer the "clean" url 🤷 

i'll close this for now but will re-open if more people or the team disagree with me
