### ISSUE TITLE
Incorrect format of heading  hierarchy in path module  doc

### ISSUE THREAD

**Issue by shenghan97** [tauri-apps/tauri-docs#304]
Hi.

It appears that the _Platform-specific_ heading in [https://tauri.studio/en/docs/api/js/modules/path](https://tauri.studio/en/docs/api/js/modules/path) is being incorrectly marked as h1 or h2. However they apparently should be much lower in the hierarchy, maybe h3 or h4. It causes problems in the table of contents on the right sidebar where _Platform-specifc_ s are intended less than their corresponding higher-level headings.

Hope it's fixed soon! 

Thanks!

**Comment by amrbashir** [comment]
We fixed this in tauri repo, will be updated in the next release. Thanks for reporting it.
