### ISSUE TITLE
tauri.localhost doesn't start

### ISSUE THREAD

**Issue by mohamadbdeir** [tauri-apps/tauri-docs#306]
I integrated tauri to my angular project, when I use` npm run tauri dev` after doing `ng serve --open` everything works fine because I have localhost:4200 running.

However, after I build the tauri app using `npm run tauri build` and I launch it, the app remains blank and in the console, I can see that 'tauri.localhost' refused to connect, meaning that there is no server running.

When I add `"embeddedServer": {
"active": true
},` in tauri.conf.json I get an error saying that additional property embeded server is not allowed

**Comment by lucasfernog** [comment]
Please follow the issue template and post the output of `tauri info`.

**Comment by lucasfernog** [comment]
Your `tauri.conf.json`'s `devPath` config value should be `http://localhost:4200`.

**Comment by mohamadbdeir** [comment]
> 

Here is the output of `tauri info`

`Operating System - Windows, version 10.0.19043 X64
Webview2 - Not installed

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.0
  yarn - Not installed

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/.angular
/.git
/.vscode
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:4200
  framework - Angular
  bundler - Webpack
`

and I already have  ` "devPath": "http://localhost:4200"`
Here is the entire  `tauri.conf.json`:
`{
  "package": {
    "productName": "opencistock",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:4200",
    "beforeDevCommand": "",
    "beforeBuildCommand": ""
  },
  "tauri": {
    
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "macOS": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false,
        "exceptionDomain": "",
        "signingIdentity": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "allowlist": {
      "all": false
    },
    "windows": [
      {
        "title": "openci",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"
    }
  }
}`

**Comment by mohamadbdeir** [comment]
> Your `tauri.conf.json`'s `devPath` config value should be `http://localhost:4200`.


Here is the output of `tauri info` :  

```
Operating System - Windows, version 10.0.19043 X64
Webview2 - Not installed

Node.js environment
  Node.js - 16.13.1
  @tauri-apps/cli - 1.0.0-beta.10
  @tauri-apps/api - 1.0.0-beta.8

Global packages
  npm - 8.3.0
  yarn - Not installed

Rust environment
  rustc - 1.57.0
  cargo - 1.57.0

App directory structure
/.angular
/.git
/.vscode
/dist
/node_modules
/src
/src-tauri

App
  tauri.rs - 1.0.0-beta.8
  build-type - bundle
  CSP - default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'
  distDir - ../dist
  devPath - http://localhost:4200
  framework - Angular
  bundler - Webpack
```

the `devPath` is already set to `http://localhost:4200`

Here is the entire `tauri.conf.json` file:

```
{
  "package": {
    "productName": "opencistock",
    "version": "0.1.0"
  },
  "build": {
    "distDir": "../dist",
    "devPath": "http://localhost:4200",
    "beforeDevCommand": "",
    "beforeBuildCommand": ""
  },
  "tauri": {
    
    "bundle": {
      "active": true,
      "targets": "all",
      "identifier": "com.tauri.dev",
      "icon": [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ],
      "resources": [],
      "externalBin": [],
      "copyright": "",
      "category": "DeveloperTool",
      "shortDescription": "",
      "longDescription": "",
      "deb": {
        "depends": [],
        "useBootstrapper": false
      },
      "macOS": {
        "frameworks": [],
        "minimumSystemVersion": "",
        "useBootstrapper": false,
        "exceptionDomain": "",
        "signingIdentity": null,
        "entitlements": null
      },
      "windows": {
        "certificateThumbprint": null,
        "digestAlgorithm": "sha256",
        "timestampUrl": ""
      }
    },
    "updater": {
      "active": false
    },
    "allowlist": {
      "all": false
    },
    "windows": [
      {
        "title": "openci",
        "width": 800,
        "height": 600,
        "resizable": true,
        "fullscreen": false
      }
    ],
    "security": {
      "csp": "default-src blob: data: filesystem: ws: wss: http: https: tauri: 'unsafe-eval' 'unsafe-inline' 'self' img-src: 'self'"
    }
  }
}
```

**Comment by mohamadbdeir** [comment]
> Your `tauri.conf.json`'s `devPath` config value should be `http://localhost:4200`.

Thanks for your help, I was able to fix the issue by using the correct path for distDir. It was set to `../dist` instead of `../dist/appName`

**Comment by mohamadbdeir** [comment]
Thanks for your help, I was able to fix the issue by using the correct path for `distDir`. It was set to `../dist` instead of `../dist/appName`
