### ISSUE TITLE
Discuss using PRs for Translation vs Crowding

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#339]
@ksnyde 

Putting this here so I don't forget it ;)

**Comment by lorenzolewis** [comment]
Docusaurus and Crowdin integration has been set up and completed, closing this one out.

**Comment by yankeeinlondon** [comment]
Nice. Is there a readme somewhere I could look at to just get my head around the solution?

**Comment by yankeeinlondon** [comment]
I think I re-openned; didn't mean to do that

**Comment by lorenzolewis** [comment]
I think it stayed closed, but no worries at all. It's just using Crowdin as the translation agent since that's the industry standard and we were already moving in that direction. https://github.com/tauri-apps/tauri-docs/blob/dev/.github/CONTRIBUTING.md#internationalization-i18n has a bit of information on it. 

If this is to look at indexing then feel free to send me a message and on Discord and we can see if there are any impacts (there won't be yet as we haven't switched on any languages on the site yet).
