### ISSUE TITLE
JavaScript API needs an index page

### ISSUE THREAD

**Issue by dragonworx** [tauri-apps/tauri-docs#340]
Following the link for the JavaScript API on `docs/development/intro` leads to a 404 as there is no `https://github.com/tauri-apps/tauri-docs/tree/dev/docs/api/js` page for the JavaScript API on `docs/api/config`.

**Expected behavior:** Clicking the link on `docs/development/intro` would land on an index page showing the Classes, Enums, Interfaces, Modules pages with preferably a short intro and any other useful links.

**Current behavior:** Clicking the link on `docs/development/intro` leads to a 404, requiring additional user navigation to get to JavaScript APIs.

**Comment by lorenzolewis** [comment]
Fixed and deployed. Thanks for catching this!
