### ISSUE TITLE
Lightmode

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#359]
- [x] Accent colours for light and dark modes (used on roadmap)
- [x] Add :hover to <a> elements #307 
- [x] Add light theming for high-contrast #307
- [x] Navbar toggle padding https://github.com/tauri-apps/tauri-docs/pull/333#issuecomment-1014601573
- [x] Search Bar overhaul
- [x] Navbar hover height
- [ ] Github icon size (make larger)
- [x] Beta badge contrast (as well as semantic warning, info, etc. colours)
- [x] Sidebar background colour
- [x] Codeblocks in light theme
- [x] Setup for macOS badge icons (below)
- [ ] Alert Colours
<img width="645" alt="Screenshot 2022-01-21 at 18 52 49" src="https://user-images.githubusercontent.com/15347255/150583834-1509c009-ec3a-4d18-9c19-5d5d7b49c730.png">

**Comment by lorenzolewis** [comment]
Keeping an eye on https://github.com/twbs/icons/issues/1094 for a linux icon

**Comment by Poopooracoocoo** [comment]
Hi does the website use prefers-color-scheme? I saw the dark theme by default despite having light mode enabled for apps and my browser. It looks like it doesn't. Should I open a new issue or is this comment enough?

**Comment by FabianLars** [comment]
@Poopooracoocoo The (unreleased) re-design which this issue is about does respect it. The current site however doesn't. I opened a small PR to change it for the live site.
Here's the preview: <https://deploy-preview-498--tauri.netlify.app>

**Comment by JonasKruckenberg** [comment]
Hey @lorenzolewis because this issue just popped up in my notifications: What colors did you use exactly for that light mode? The colors from figma?

**Comment by lorenzolewis** [comment]
> Hey @lorenzolewis because this issue just popped up in my notifications: What colors did you use exactly for that light mode? The colors from figma?

I tried to keep them pretty organised here, the first set are dark mode, but you can see light mode in there as well. 

https://github.com/tauri-apps/tauri-docs/blob/feat/v1/src/css/custom.css

**Comment by lorenzolewis** [comment]
Closing this out as we now have light mode (will continue to tweak it where necessary)
