### ISSUE TITLE
Fill FAQ before first release candidate

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri-docs#380]
quote https://discord.com/channels/616186924390023171/662624589037436928/936279456031596615:
> Anyways, the FAQ is something we can have on the website but we must keep it small and notify people there are issues, discussions and eventually Discord (not Discord first, because it means people will flood the chans instead of the issues, or even both).

**Comment by lorenzolewis** [comment]
I'm going to close this one out. I've been going through and adding to some recent PRs for any issues that would be good for a FAQ entry, but lmk if there are additional ones we should throw on there
