### ISSUE TITLE
Broken JS API docs link

### ISSUE THREAD

**Issue by wpbonelli** [tauri-apps/tauri-docs#395]
The [link](https://tauri.studio/docs/api/js/index) to the JS API docs on the [intro page](https://tauri.studio/docs/development/intro) is broken, just a friendly fyi
![Screen Shot 2022-02-05 at 10 59 18 PM](https://user-images.githubusercontent.com/10502868/152667245-1c2443dc-59ec-43f8-a3de-3c2317fc29ba.png)

**Comment by FabianLars** [comment]
Hey, thanks for reporting it! ❤️ 

We're in the process of refactoring the docs and its structure (see the feat/v1 branch), so I'm gonna close this issue as the problematic page isn't part of the docs anymore.
