### ISSUE TITLE
Make roadmap more intuitive

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#40]
Colors explaining a feature state from the roadmap is not explicit enough and not good enough for accessibility.

Since Docusaurus doesn't provide icons font, we need to pick one first.

**Comment by Laegel** [comment]
@nothingismagick suggested https://themify.me/themify-icons

**Comment by nothingismagick** [comment]
Here are the icons I chose for the last roadmap:

https://github.com/tauri-apps/tauri.studio/blob/02fc6aa9331a9c7300c67755f8efd8ef4b015f9a/docs-generator/src/pages/Landing.vue#L269-L454
