### ISSUE TITLE
Add the default Docusaurus "search" functionality

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#41]
Here's the doc to follow: https://v2.docusaurus.io/docs/search

**Comment by nothingismagick** [comment]
Are we going to look into using meilisearch?
https://docs.meilisearch.com/resources/comparison_to_alternatives.html

**Comment by Laegel** [comment]
Yup!
Since Docusaurus is React-based, we'll follow this guide: https://docs.meilisearch.com/instant-search-react-app/#introduction

**Comment by Laegel** [comment]
Using https://github.com/meilisearch/docs-searchbar.js for the website integration
We now need to decide:
## How to index our docs
- from the repo, creating a JSON file with a script;
- with MeiliSearch scrapping tool: https://github.com/meilisearch/docs-scraper.

I'd say the former is more efficient than the latter but way harder to setup.

## Where to host MeiliSearch engine
- DigitalOcean;
- Netlify Functions.

**Comment by nothingismagick** [comment]
lets do digital ocean, we have credits there

**Comment by Laegel** [comment]
Tauri's MeiliSearch engine is up and lives at https://search.tauri.studio
Next step: indexing content in a GitHub Action, right after all docs have been created/updated.
We should push a new indexation for each release: `https://search.tauri.studio/indexes/{{TAURI_VERSION_TAG}}/documents` in order to have proper versioning.
Note: `TAURI_VERSION_TAG` should use underscores instead of dots, dots not being valid for MeiliSearch index uid.
