### ISSUE TITLE
Enable documentation versioning

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#42]
Sooner or later, we'll need to enable the docs versioning: https://v2.docusaurus.io/docs/versioning/

Since we're not stable yet, I'm unsure this should be done ASAP. But let's keep that in a corner of our heads.

**Comment by chippers** [comment]
bumping and pinning because I believe this is a blocking issue for a stable 1.0 release

**Comment by lorenzolewis** [comment]
The groundwork has been laid for this and the CONTRIBUTING page outlines how to do this. Closing this issue.
