### ISSUE TITLE
Add guide: Tauri + HTML,CSS,JS

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri-docs#441]
# TODO

Add a guide to `architecture` laying out how to use Tauri without a frontend bundler using plain HTML, CSS, and JS.

## Details

- `devPath` and `distDir` can point to file system paths
- when `devPath` is a file path, Tauri will provide hot reloading

**Comment by chippers** [comment]
I am interested in this guide as a "base technologies" type of thing, where the minimal inputs meet Tauri. I can't recall if the CLI hot reloads for a file system `devPath`

**Comment by FabianLars** [comment]
> I can't recall if the CLI hot reloads for a file system devPath

It doesn't but i think we said we want to implement it. Currently you have to ctrl+c the cli to pick up the changes.

**Comment by JonasKruckenberg** [comment]
> It doesn't but i think we said we want to implement it. Currently you have to ctrl+c the cli to pick up the changes.

Well 😂 I'm glad I didn't write this guide

**Comment by Laegel** [comment]
Can't remember if we said it was a good or a bad idea to have this `devPath` FS watcher. Probably a good one, but we wouldn't do it because of the code freeze. This could be a "good first issue", right?

**Comment by dmz76** [comment]
I'm very interested in this as I have a project that is just a simple educational app in CSS, HTML and EaselJS that I would really like to migrate from Electron. Using Electron I didn't need to think about a server and I could find enough examples/clues to get it to work. As it stands I have no idea what to do past initial setup.
Any progress on the guide?

**Comment by FabianLars** [comment]
Not much progress as we're in the process of rewriting _everything_, so it makes sense to wait with new doc pages after that's done.
We can look into providing some first some pointers in this issue if we find the time.

**Comment by dmz76** [comment]
Fair enough. I actually just got my project to work, just without sound. I'm hopeful!
