### ISSUE TITLE
bash: $: command not found...

### ISSUE THREAD

**Issue by blfpd** [tauri-apps/tauri-docs#454]
The shell/bash code snippets shouldn’t start with the prompt sign `$`, especially if there is this super practical <kbd>Copy</kbd> button.

```bash
$ sudo dnf install […]
```
To be replaced by:
```bash
sudo dnf install […]
```

This prompt may confuse beginners, and is less and less _everywhere_. 

Found in the [Getting Started page](https://github.com/tauri-apps/tauri-docs/blob/dev/docs/getting-started/setting-up-linux.md), might be found elsewhere.

I’m ready to do a merge request if you agree with the purpose of this issue.

**Comment by FabianLars** [comment]
imo the $ is generally a good thing to include, but the copy button really defeats its purpose here. For me the best case would be if it's not selectable (like in electron docs) and if the button could ignore it too.

If we can't implement it like this i'd vote for removing it too.

**Comment by blfpd** [comment]
> imo the $ is generally a good thing to include

I’ve always found it more confusing than helpful. It’s quite obvious if there is `sudo`, and no filename attached to the snippet, it to be typed in a terminal. If this is not obvious, better write it down in plain text before the listing.  
But neither of us is beginner, so at this point this is opinion/bike-shedding.

I’d rather remove them here, than adding them on https://tauri.studio/docs/getting-started/beginning-tutorial

**Comment by FabianLars** [comment]
> I’d rather remove them here, than adding them on https://tauri.studio/docs/getting-started/beginning-tutorial

Well adding them there wouldn't make sense as they try to be cross-platform.

> I’ve always found it more confusing than helpful.

True, the only somewhat helpful thing _for me_ is if it's about root # (which obviously is super rare).

> It’s quite obvious if there is sudo [...]

As harsh as this may sound, we can't rely on common sense. But i agree that a) the "inconsistency" is annoying and b) the people the sign is actually meant for (beginners) may indeed not know what $ vs # means. So removing it and maybe adding a note/warning is fine imo.
Additionally i'd really like to see some styling changes that would make it obvious that we're talking about terminal commands (ideally some non-root hint?), but i can't imagine what that would look like at this point cc @lorenzolewis
