### ISSUE TITLE
Inline docs/syntax for allowlist scopes in config docs

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri-docs#468]
Example: <https://tauri.studio/docs/api/config#tauri.allowlist.shell.scope> - how should ~~a user~~ Jonas know what `ShellAllowlistScope` is?

**Comment by JonasKruckenberg** [comment]
I don't even know what that is myself 😂

**Comment by lorenzolewis** [comment]
This will be fixed by #604 right?

**Comment by lucasfernog** [comment]
Yeah I believe so.

**Comment by FabianLars** [comment]
Yep
