### ISSUE TITLE
[patterns]: New pattern -> devtool

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-docs#47]
So, with guijs and theia, we've seen a new pattern begin to emerge, and I think we should start thinking about adding a new pattern page. It is a "lowish-security" pattern, because we are currently shipping shell-script orchestrators in order to be able to kill spawned threads. 

Nevertheless, it is a powerful and very useful pattern.

**Comment by simonhyll** [comment]
Is this still something we want covered one way or another in 2.0 @nothingismagick ? Tracking it for 2.0 pending input.
