### ISSUE TITLE
[i18n] add simplified Chinese

### ISSUE THREAD

**Issue by GuoJikun** [tauri-apps/tauri-docs#473]
It is suggested to add simplified Chinese

**Comment by FabianLars** [comment]
Our docs and its structure are too unstable for i18n right now, but once that is no more (when we release tauri@v1-stable) we will start translating again (most likely via crowdin.com again)

**Comment by peterroe** [comment]
> Our docs and its structure are too unstable for i18n right now, but once that is no more (when we release tauri@v1-stable) we will start translating again (most likely via crowdin.com again)

Maybe I can help translate Chinese documents after the official version is released @FabianLars

**Comment by GuoJikun** [comment]
> 我们的文档及其结构对于i18n来说太不稳定了，但是一旦不再不稳定（当我们发布tauri@v1-stable时），我们将再次开始翻译（很可能再次通过 crowdin.com）

Look forward to the official version

**Comment by cxgreat2014** [comment]
Look forward to the tauri@v1-stable
