### ISSUE TITLE
Windows Application Distribution page has a bug

### ISSUE THREAD

**Issue by medmin** [tauri-apps/tauri-docs#479]
In this page, https://tauri.studio/docs/distribution/windows

This is the first sentence : Tauri applications for Windows are distributed **either** with a Microsoft Installer (.msi files). 

You have **either**, what about the **or** ?

**Comment by JonasKruckenberg** [comment]
Indeed 😅. @lucasfernog did you mean to add "and .exe format" or shall we just remove the either?

**Comment by FabianLars** [comment]
The .exe is not really generally distributable right now, so probably better to remove it.

**Comment by lucasfernog** [comment]
Yeah my bad, just mention MSI.
