### ISSUE TITLE
document supported versions

### ISSUE THREAD

**Issue by JonasKruckenberg** [tauri-apps/tauri-docs#512]
We should document what versions of our dependencies we support.

> I know this should be implementrd over at tauri-docs but let’s discuss this here first.

## OS
- macOS: `>= 10.15`
- window: `>= win10`
- linux: ???

## Other
- Node.js: `>= 12.13.0` (Should this be raised to `12.22.0` to support  napi 8? )
- Rustc: `>= 1.56.0` (edition 2021)
- Cargo: `>= 1.56.0` (edition 2021)

**Comment by lorenzolewis** [comment]
I feel like this is something that should be on the Tauri repo readme, possibly right under this table:
<img width="823" alt="Screenshot 2022-06-19 at 16 17 51" src="https://user-images.githubusercontent.com/15347255/174488148-524e3f97-2351-4e30-918b-9837d7204517.png">

Would also be good to specific if these are development requirements and/or distributed client requirements.

**Comment by lucasfernog** [comment]
Good idea @lorenzolewis.

Only api.js and core are shipped in a Tauri binary, the others are all developer tools.

**Comment by lorenzolewis** [comment]
Closing this via https://github.com/tauri-apps/tauri/pull/4432
