### ISSUE TITLE
[docs] MenuItem::About() expected 2 arguments 

### ISSUE THREAD

**Issue by Janaka-Steph** [tauri-apps/tauri-docs#537]
Writing `add_native_item(MenuItem::About("Blabla".to_string()))` now returns error `expected 2 arguments`  
Please add an example in the doc `https://tauri.studio/docs/guides/menu`.

Here `https://docs.rs/tauri-runtime/0.3.4/tauri_runtime/menu/enum.MenuItem.html#variant.About` it doesn't say if MacOS is supported. It doesn't seem so, metadata are not displayed.

**Comment by lucasfernog** [comment]
The documentation does state that the metadata is only applied on Linux.

**Comment by simonhyll** [comment]
Closing this based on Lucas answer.
