### ISSUE TITLE
Search component covers Tauri logo in mobile

### ISSUE THREAD

**Issue by hslee2008** [tauri-apps/tauri-docs#574]
# Problem
Currently, the website's search component covers the logo.
It's not a huge problem but it is certainly annoying when browsing the docs in mobile.

![tauri studio_](https://user-images.githubusercontent.com/78584173/167277694-1bf03ac8-7b98-4a31-9a0c-f7c4a03b067f.png)

# Solution
Make a button when clicked, opens either a modal or shows input that only works on mobile.

**Comment by lorenzolewis** [comment]
Going to close this, tracking in #372
