### ISSUE TITLE
Guide Improvements

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#593]
Using this to track enhancements to migrated docs that aren't show-stoppers to migrate and that'd like to implement in the near future

# Concepts
- [ ] https://github.com/tauri-apps/tauri-docs/pull/590#discussion_r871358377
- [ ] Windows 11 support https://github.com/tauri-apps/tauri-docs/pull/590#discussion_r871473653
- [ ] Possibly migrate development/security to concepts/security https://github.com/tauri-apps/tauri-docs/pull/590#discussion_r871580047 
- [x] https://github.com/tauri-apps/tauri-docs/pull/609
- [ ] https://github.com/tauri-apps/tauri/issues/2731

# Build Guides
- [x] https://github.com/tauri-apps/tauri-docs/issues/441
- [ ] https://github.com/tauri-apps/tauri-docs/issues/440
- [x] https://github.com/tauri-apps/tauri-docs/issues/431
- [x] https://github.com/tauri-apps/tauri-docs/issues/456
- [x] https://github.com/tauri-apps/tauri-docs/issues/445
- [x] https://github.com/tauri-apps/tauri-docs/issues/443
- [ ] https://github.com/tauri-apps/tauri-docs/issues/442
- [ ] https://github.com/tauri-apps/tauri-docs/issues/432
- [x] https://github.com/tauri-apps/tauri-docs/issues/741

# Misc.

- [ ] Change distribution/publishing into a more summarised version of building and set it as building/README.md
- [ ] Remove distribution/windows, distribution/macos, and distribution/linux, fill in any dropped content into their respective building pages
- [ ] Use the distribution section to focus on code signing, App Store deployment, and updater distribution

**Comment by FabianLars** [comment]
Gonna hijack this one to remind myself to add temporary 301 redirects for _all_ guides after #590 is merged, because too many people use google to actually navigate the docs.

**Comment by good-praxis** [comment]
since we're keeping track of [tauri#2731](https://github.com/tauri-apps/tauri/issues/2731), I'd suggest also keeping track of [tauri#4163](https://github.com/tauri-apps/tauri/issues/4163), both being related to the AppImage build process and `PATH` resolution

**Comment by lorenzolewis** [comment]
@JonasKruckenberg Hijacking this to have a conversation on Getting Started guides.

I think it would be good to have an outline of what topics the different guides cover before we get into writing them all (would help those in the community that want to contribute as well). There is a lot of crossover and this could help us more easily build out the fragments. 

Something along these lines:

- Tauri + Vite
  1. Install Vite
  2. Install Tauri
  3. Setup web assets
  4. Setup Tauri command
- Tauri + Typescript
  1. Install TS
  2. Install Tauri
  3. ... etc ...

**Comment by lorenzolewis** [comment]
@JonasKruckenberg we talked about adding logos to the landing page for the getting started guides, could use something like we are in the accolades section here: https://github.com/tauri-apps/tauri-docs/blob/dev/blog/tauri_1_0.mdx#accolades

We'd have to manually add each new guide, but don't think that would be an issue

**Comment by JonasKruckenberg** [comment]
Yeah, I don't think we'll add that many so keeping up to date would become a problem 😅

So yeah that'd be cool!

**Comment by adsick** [comment]
there is a broken video embedding in https://github.com/tauri-apps/tauri-docs/tree/dev/docs/guides

**Comment by adsick** [comment]
there is a broken link "HTML/CSS/JS"
https://tauri.app/v1/guides/getting-started/html-css-js should be 
https://tauri.app/v1/guides/getting-started/setup/html-css-js

fix this file: https://github.com/tauri-apps/tauri-docs/blob/dev/docs/guides/getting-started/setup/README.mdx
