### ISSUE TITLE
[feat] Confusing "Getting Started" Web-Layout

### ISSUE THREAD

**Issue by haasal** [tauri-apps/tauri-docs#610]
### Describe the problem

The [Getting Started](https://tauri.studio/v1/guides/getting-started/beginning-tutorial/) page on the tauri website is rather confusing as all Headers are `h3`. It might be difficult for some to understand what belongs to "*Start a new tauri project*" and what to the "Initialize Project" Subject. 

(I just noticed there is some minor inconsistency with the colons in the headers)

### Describe the solution you'd like

I would change the layout to:

```html
<h3>Start a New Tauri Project<h3>

<h3>Add Tauri to Existing Project<h3>

<h4>1. Some description for the first step<h4>
<h4>2. Initialize Tauri in Your App<h4>
<h4>3. Check tauri info to Make Sure Everything Is Set up Properly<h4>
```

This could even help with SEO to some extend.

### Alternatives considered

I don't even know if I understood the layout completely. If someone knows exactly whats going on there please provide a better alternative. 

### Additional context

If step 2 and 3 on the website don't even belong to the  on the *Add Tauri to Existing Project*-step it's a completely different issue. Because then it's even more confusing. I didn't have to do `cargo tauri init` to generate the src-tauri folder. It was generated automatically in step *Start a New Tauri Project*. The site might be simply outdated.

**Comment by lorenzolewis** [comment]
I'd like to take another look at this once we merge https://github.com/tauri-apps/tauri-docs/pull/635 in. I think that will naturally give us some better context to improve this specific page.

**Comment by lorenzolewis** [comment]
Closing this as we've had a LOT of changes and now have multiple guides available that hopefully have a more friendly layout: https://deploy-preview-773--tauri.netlify.app/v1/guides/getting-started/setup/

Please let us know if there are any additional points we can take to organise the guides :D
