### ISSUE TITLE
[docs] Guide for debugging Rust (ex. with LLDB via VS Code)

### ISSUE THREAD

**Issue by dallonf** [tauri-apps/tauri-docs#628]
It would be really nice to be able to debug the Rust code in a Tauri app. I've done it before with pure Rust projects, but I'm very fuzzy on how I would attach to a Tauri process. The current docs only describe how to use `println!`-based debugging.

**Comment by Laegel** [comment]
Hey @dallonf , you're right: this would be an amazing thing to document. :)

**Comment by JonasKruckenberg** [comment]
I haven't used GDB or LLDB much so I can't add any more details, but this is my starting point: https://jonaskruckenberg.github.io/tauri-docs-wip/development/debugging.html#gdb

So if you have more tips to add, feel free to open a PR!

**Comment by lucasfernog** [comment]
I'm considering integrating debugging with LLDB in the tauri VS Code extension.
