### ISSUE TITLE
Evergreen i18n build

### ISSUE THREAD

**Issue by lorenzolewis** [tauri-apps/tauri-docs#673]
Create a GitHub action to continually pull the latest translations and launch a deploy preview in Netlify.

Note: We may want to enable preview ALL languages we support in Crowdin, but we won't want to deploy those until we manually approve them and update them in the config as a core team. I'm not exactly sure what this would look like just yet.

# References
- Netlify will automatically build anything that we open a PR against in `main`. We just need to enable additional languages for the build in this case
- Add a context to https://github.com/tauri-apps/tauri-docs/blob/dev/netlify.toml to run an alternative command for any branches with a specific name (such as `i18n-preview`). This should match the `[build]` context we already have, but somehow we need to inject to build additional languages to Docusaurus. Normally we'd do this through the config file, but we only want to update that file if we're actually ready to DEPLOY an additional language. 
  - [Netlify docs for additional contexts ](https://docs.netlify.com/configure-builds/file-based-configuration/#deploy-contexts)
- Right now the unsolved bit is how to tell Docusaurus to build for additional languages without actually adding them to the config. I'm not sure if this is something we could achieve by passing as CLI arguments to `docusaurus build` or not.
- Once all of the commands are set up, we'd just create a GitHub action that would open a PR with code in `main` against `main`. This is just to trigger Netlify to run a deploy preview there

**Comment by lorenzolewis** [comment]
Tagging @Byacrya

**Comment by lorenzolewis** [comment]
We could have an alternative build file with additional languages and pass that to the CLI to build: https://docusaurus.io/docs/cli#options-1

Would just like to build that dynamically if possible at all so that we don't get de-sync issues between the files.

**Comment by lorenzolewis** [comment]
I did some work on this today and am coming up with a few issues. I have the automation in place, but we keep getting hung up on the link checking during build:

```
Exhaustive list of all broken links found:

- On source page path = /af/v1/guides/architecture/isolation:
   -> linking to ../../development/security.md#threat-models (resolved as: /af/v1/development/security.md)
   -> linking to ../../features/events.md (resolved as: /af/v1/features/events.md)
   -> linking to ../../testing/webdriver/introduction.md (resolved as: /af/v1/testing/webdriver/introduction.md)

- On source page path = /af/v1/guides/getting-started/setup/html-css-js:
   -> linking to ../../features/command.md (resolved as: /af/v1/guides/features/command.md)

- On source page path = /af/v1/guides/getting-started/setup/vite:
   -> linking to ../../features/command.md (resolved as: /af/v1/guides/features/command.md)
```

I know we're focusing on Chinese right now, but this is the same across all languages. It may be that we just need to adapt our links to be correct but I didn't have time to look into it yet.

I'm working on this here: https://github.com/tauri-apps/tauri-docs/tree/feat/i18n-evergreen

**Comment by lorenzolewis** [comment]
https://github.com/tauri-apps/tauri-docs/pull/701 This one may fix it, but needs to be deployed first and then see if all the i18n translations get fixed automatically once they're pushed to crowdin

**Comment by lorenzolewis** [comment]
Using this to keep notes, but we want to look at some way of caching the "build" folder between crowdin runs or else our run times will go crazy turning on extra languages

**Comment by FabianLars** [comment]
Either that or limit runs to 1 every X hour(s) 🤷

**Comment by lorenzolewis** [comment]
Not even, every 1 day. I just hit an "out of memory" error on build only halfway through the list of languages, so it's a fun journey.

**Comment by lorenzolewis** [comment]
Might have to switch up the deployment strategy and do multi-domain because the build times just aren't playing friendly at all https://docusaurus.io/docs/i18n/tutorial#multi-domain-deployment
