### ISSUE TITLE
Add Guide: Tauri + SvelteKit

### ISSUE THREAD

**Issue by FabianLars** [tauri-apps/tauri-docs#741]

**Comment by FabianLars** [comment]
ah yes, i'm a project board expert 😂 didn't mean to open this (yet)

**Comment by JonasKruckenberg** [comment]
Iconic

**Comment by Eudritch** [comment]
I made a [Tauri + SvelteKit template](https://github.com/Eudritch/clean-tauri-sveltekit), which pretty much explains itself.

**Comment by lorenzolewis** [comment]
As an update, SvelteKit has reached the 1.0 RC https://www.reddit.com/r/sveltejs/comments/xa03y7/sveltekit_has_entered_its_release_candidate_phase/ so we could look more closely at writing a guide without breaking changes coming in (hopefully).

**Comment by FabianLars** [comment]
quite happy that we "waited" with the guide because they reworked basically _everything_ 1 or 2 weeks ago 😂

**Comment by lorenzolewis** [comment]
Yup, that routing system re-write was a big one, but I like the way it works now more than before it.

I wonder how we approach covering Svelte, SvelteKit, and Vite considering they have a lot of crossover (same for CTA as well).
