### ISSUE TITLE
Tauri showcase badges & moderation notice

### ISSUE THREAD

**Issue by Laegel** [tauri-apps/tauri-docs#76]
Since Tauri's major concern is about security, we'll provide audits to the projects registered in the showcase for a fee to our OpenCollective. 
Those projects will get a badge (displayed in the showcase) as a gage of security:

![tauri-shield](https://user-images.githubusercontent.com/3584791/86231956-96a1e380-bb93-11ea-8a8a-c64cbd332687.png)

Tauri's `special focus` projects (like guijs) will get another badge, like a star (to confirm).

We should also add a notice to let the community know we won't accept illegal/explicit content in the showcase.

**Comment by Beanow** [comment]
> for a fee to our OpenCollective

When working out the specifics, should make sure we're not running into issues making a 'quid pro quo' donation. Possibly we need to treat it as compensation, not a donation.

**Comment by lorenzolewis** [comment]
Is this covered by https://github.com/tauri-apps/awesome-tauri?

**Comment by lorenzolewis** [comment]
Going to close this one out
