### ISSUE TITLE
[feat] When will Go be supported

### ISSUE THREAD

**Issue by wburningham** [tauri-apps/tauri-docs#772]
### Describe the problem

When will Go be supported as a backend language? The roadmap section on https://tauri.app says that Go bindings are planned. I'd like to be able to subscribe to updates on a milestone.

### Describe the solution you'd like

Go as a backend language

**Comment by JonasKruckenberg** [comment]
There is currently no work on bindings being done, we have plans to support languages (as the roadmap suggests) but need to lay a lot of groundwork before enabling stable bindings.

**Comment by wburningham** [comment]
@JonasKruckenberg how can I follow along with progress and changes to the roadmap? Asking because a similar request was made for python (#4670) and that issue is still open (are issues the source of truth or is there a different mechanism?).

**Comment by nothingismagick** [comment]
There are two things you can look into:

The "best" we can do right now, is to point you at this example in the main repo:
https://github.com/tauri-apps/tauri/tree/dev/examples/tauri-dynamic-lib

It shows how to instrument Tauri with a cdylib - which can be a starting point. 

The other "best", would be to consider joining the working group and actively contribute your knowledge to the field.

**Comment by nothingismagick** [comment]
But. as a final note, you will still most likely need at least some rust in your project, as there is no event horizon anticipated where we rewrite in go.
