### ISSUE TITLE
Example code not working for me

### ISSUE THREAD

**Issue by dimiour** [tauri-apps/tauri-docs#787]
The example for calling rust from the front end does not seem to work:
![image](https://user-images.githubusercontent.com/98242336/180005679-ba01d5c6-6b63-4551-a50d-2ac90b1d599a.png)
I made some modifications to the code (I don't know much javascript I just read the errors) like adding a slash to the import path, and removing the const because it couldn't be called twice. I got stuck on this error though:
![image](https://user-images.githubusercontent.com/98242336/180005753-48807c5d-f69a-48f6-81fa-ce6c6d59805b.png)

**Comment by lorenzolewis** [comment]
You shouldn't be using a leading slash, it's the same as the guides. Make sure you've added the NPM package as well. 

Note that you only should define invoke once (you can decide which method to use based on the code comments). 

The Vite guide may be help for for you to follow along with and make sure you have everything set up correctly. https://tauri.app/v1/guides/getting-started/setup/vite
