### ISSUE TITLE
Staging Site

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-docs#8]
It would be good to put this up on a staging site so that we can get some members of the team to review it. @khionu / @nklayman - would you be up to throwing this up on now.sh or some free service like that?

@jbolda - maybe an action would be good too.

Thoughts?

**Comment by jbolda** [comment]
Where will the final host be? I have an action I use that does Netlify Deploy previews and prod, or they have their own actions integration (and we can apply for the open source license for more build minutes).

**Comment by khionu** [comment]
If we can make use of the same provider for production and staging, that would be best, imo.

**Comment by nothingismagick** [comment]
Then I guess we should use digital ocean.

**Comment by nklayman** [comment]
I could probably set up a ci on GitHub actions that builds the website as a container, uploads the image to the GitHub image registry, and then a digital ocean kuberenetes cluster could pull the image and set up an instance or two of it for hosting. We could have a build for stable and staging and run both versions of the site on the same cluster. We would use the ingress controller to direct traffic to either the staging or stable version of the site. This shouldn't be very expensive as we can start with a single $5 droplet and the control plane nodes are free.

**Comment by jbolda** [comment]
We are thinking for ease of devops to go with Netlify and apply for the open source access. We also get the deploy previews in our PRs which is some great DX.

**Comment by jbolda** [comment]
Netlify has been all set up, and it will handle both our staging and production sites.
