### ISSUE TITLE
The Meilisearch index is not refreshed

### ISSUE THREAD

**Issue by olivierlemasle** [tauri-apps/tauri-docs#864]
The Meilisearch indexing action has been commented out because it should not run for all Pull Requests: https://github.com/tauri-apps/tauri-docs/blob/76c81180323730dac285a83cb710a57d2d7710fd/.github/workflows/update-docs.yml#L85-L96

However, it should still run when deploying new versions of the documentation.

The index is currently outdated, e.g.:
- When searching "Benchmarks", no result are found (despite a new page "Benchmarks")
- When searching "Bridge", a result "Bridge > architecture" is found, which leads to a Page Not Found error (it is the draft "recipe" on Bridge architecture).

**Comment by FabianLars** [comment]
I just re-ran the indexer for the new References category. it will still pick up the drafts until one of us has the time and energy to continue working on our search x)

p.s. the workflow code is still for the old search and just kept as a reference.

**Comment by olivierlemasle** [comment]
Thanks @FabianLars; however the new links are broken in the results (missing `/v1/`).

**Comment by FabianLars** [comment]
Oh yeah, I'll fix that tomorrow. Thanks!
