### ISSUE TITLE
[design] Searchbar too wide for navbar at 1366px wide display

### ISSUE THREAD

**Issue by electrolyte-orb** [tauri-apps/tauri-docs#865]
## You can see here
at 1366px wide display(1080p scaled up by ~150%), the navbar becomes inaccessible:

![Tauri Issue](https://user-images.githubusercontent.com/55880176/189470834-cc26d89a-764a-49c6-85ed-f7306d7a7d41.png)

**Comment by lorenzolewis** [comment]
Closed by #866
