### ISSUE TITLE
Add install instructions for linux distributions that are not using apt, e.g. arch, fedora, etc

### ISSUE THREAD

**Issue by hugohabicht01** [tauri-apps/tauri-docs#88]
It would be quite useful to add install instructions for other linux distributions as well, because the names of the needed packages are completly different and there are quite a lot of people out there who using stuff that isn't based on debian.

**Comment by Laegel** [comment]
Hey @hugohabicht01, thanks for your insight. 
There are many Linux distributions, we've started with Debian-based because it's the most common one. 
But you're right, each distro may have its own specific setup. The current page layout will need some adjustments to show the various distros steps, I'll take care of that. 
Suggestions of missing distros and instructions are welcome. :)

**Comment by Akiyamka** [comment]
Hello @hugohabicht01,
I wrote the instruction for Fedora 32 Workstation, of which I am a user:
Some packages just debian specific, so they will have to be replaced with analogues:

- `libwebkit2gtk-4.0-dev` replace with `webkit2gtk3-devel.x86_64`
- `build-essential` tools in fedora located in group  "C Development Tools and Libraries". 
- `libssl-dev` replace with openssl-devel
-  `appmenu-gtk3-module` and `ibgtk-3-dev` not required (are included in packages above or already in the system)

Additional note - I not use bash installer for rust, and install rust and cargo from fedora repo.
So summary, what I install for successful tauri bulid on fedora:
```
dnf install webkit2gtk3-devel.x86_64
dnf install openssl-devel
dnf group install "C Development Tools and Libraries"
dnf install rust
dnf install cargo
```
All these packages are in the fedora's built-in repositories (in fedora-updates.repo) so there is nothing additional to configure.

P.S. What inside in "C Development Tools and Libraries"?
```
 Description: These tools include core development tools such as automake, gcc and debuggers.
 Mandatory Packages:
   autoconf
   automake
   binutils
   bison
   flex
   gcc
   gcc-c++
   gdb
   glibc-devel
   libtool
   make
   pkgconf
   strace
 Default Packages:
   byacc
   ccache
   cscope
   ctags
   elfutils
   indent
   ltrace
   perf
   valgrind
 Optional Packages:
   ElectricFence
   astyle
   cbmc
   check
   cmake
   coan
   cproto
   insight
   nasm
   pscan
   python3-scons
   remake
   scorep
   splint
   trinity
   yasm
   zzuf
```

**Comment by amrbashir** [comment]
# Arch 
### Install all with one command:

`pacman -S webkit2gtk base-devel openssl appmenu-gtk-module 
gtk3 curl squashfs-tools`

### Packages Are: 
 1. `webkit2gtk` replaces `libwebkit2gtk-4.0-dev`
 2. `base-devel` replaces `build-essential`
 3. `openssl` replaces `libssl-dev`
 4. `appmenu-gtk-module` replaces `appmenu-gtk3-module`
 5. `gtk3` replaces `ibgtk-3-dev`

**Packages you might need for bundling the app:**
 1. `squashfs-tools`
