### ISSUE TITLE
[Feature request] Add RSS feed for Blog

### ISSUE THREAD

**Issue by NeoEvaX** [tauri-apps/tauri-docs#916]
The Tauri blog has very important release information. Many blog software out there includes an auto generated rss.xml file that many applications can subscribe to and look for changes. This would allow new posts to get to a wider range of people who may not check the blog itself often enough.

Posting a new blog entry would just regenerate the RSS file that needs to be accessible.  

Working group member FabianLars, on discord, suggested I add this Feature request.

**Comment by dym-sh** [comment]
since moving to the `beta.` subdomain, rss module of static-gen pipeline got disabled?

**Comment by FabianLars** [comment]
Right, the new blog doesn't support rss yet. Let's reopen this issue.

**Comment by lorenzolewis** [comment]
Let me take this on as I think I can do it fairly easily upstream for the new site.

**Comment by simonhyll** [comment]
Vitor and I are working on it :)

**Comment by simonhyll** [comment]
Will track this in #1845 instead.
