### ISSUE TITLE
Add the GitHub extension instructions

### ISSUE THREAD

**Issue by nothingismagick** [tauri-apps/tauri-docs#92]
This needs to be extended:
https://tauri.studio/docs/development/publishing

with information about this:
https://github.com/tauri-apps/tauri-action

especially notable: you can just ship an app that has a dist (no tauri integration)

**Comment by simonhyll** [comment]
We will be covering this in the Distribute section of the guides, and probably the tauri-action specifically in a recipe.
Tracking for 2.0.

**Comment by simonhyll** [comment]
Closing this in favour of #1273 which is effectively about the same thing.
