### ISSUE TITLE
Feature request: anchor links on the api/config page

### ISSUE THREAD

**Issue by lucasfernog** [tauri-apps/tauri-docs#95]
Currently, the config page only have anchors on the main headings. It would be useful if we could anchor the inner properties aswell (seems like the `anchorify` class does nothing). I've tried to do it but there's a lot of relative positioning in there, so it needs a rewrite I guess.

**Comment by Laegel** [comment]
It works (https://tauri.studio/docs/api/config#build.devPath) but it's missing the hash symbol that allows users to copy the reference on click. I wasn't sure people would use it so I didn't implement that yet.

**Comment by lucasfernog** [comment]
Oh you're right I can do it manually. I guess we just need to let the team knows it so we can remember and use that when we help someone.
