### ISSUE TITLE
[docs] cannot open tauri.app properly

### ISSUE THREAD

**Issue by drharryhe** [tauri-apps/tauri-docs#951]
when try to open the document website, got the following page

![image](https://user-images.githubusercontent.com/4024888/197671166-b2b27340-4aa8-40a2-aa06-63003379c3b9.png)

**Comment by nothingismagick** [comment]
I cannot even replicate that error if I turn off CSS and Javascript. It does look like what happens sometimes on VERY, slow connections... Will need more info to triage.

**Comment by drharryhe** [comment]
> I cannot even replicate that error if I turn off CSS and Javascript. It does look like what happens sometimes on VERY, slow connections... Will need more info to triage.

thanks for the reply. when i close my proxy, it looks fine now. (actually, with my proxy, i can visit github, google etc properly, do i did not think of a connection issue)

**Comment by nothingismagick** [comment]
ok, cool.
