### ISSUE TITLE
Rust toolchain for windows

### ISSUE THREAD

**Issue by brahimABD98** [tauri-apps/tauri-docs#984]
While setting up Tauri for first time on **windows** I didn't know that I had to switch the rust toolchain from 
the default windows-gnu to windows-msvc ,hence when I didn't have the right toolchain, it led to this error 

![image](https://user-images.githubusercontent.com/47871510/201743555-8a8557e5-905e-46e0-8d31-a42d1c3db245.png)

- Adding additional section with commands on how to see the current toolchain is currently being used how to switch the correct windows-msvc 

 List installed toolchains
```
rustup toolchain list
 ```
Change the default toolchain
```
rustup default <toolchain>
````
change the toolchain for the current repo only
```
rustup override set <toolchain>
```

**Comment by amrbashir** [comment]
please consult cargo/rustup docs for this https://rust-lang.github.io/rustup/concepts/toolchains.html
