### ISSUE TITLE
show the window after closed and when in system tray

### ISSUE THREAD

**Issue by lgmadurange** [tauri-apps/tauri-docs#990]
I build an application , when i clicked the close window, it automatically goes to system tray with this command

`.run(|_app_handle, event| match event {
          tauri::RunEvent::ExitRequested { api, .. } => {
            api.prevent_exit();
        }
        _ => {}
        });`

but after it goes to the system tray i want to get it show when i click the system tray icon, 
what should i have to do that, what is the code that i should want to use,

**Comment by FabianLars** [comment]
If you actually let the window close, then you need to open it by creating a new one with https://docs.rs/tauri/latest/tauri/window/struct.WindowBuilder.html
If hiding the window works too (faster, but wasteful) it would be a bit easier as shown here https://tauri.app/v1/guides/features/system-tray - i know that this guide has lots of room for improvements and we try to get to it as soon as we can.
